# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:/.core/dev/tapp/Tapp/Maya/lighting/resources/dialog.ui'
#
# Created: Tue Jan 03 18:42:35 2017
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(336, 886)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.addRimLight_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addRimLight_pushButton.sizePolicy().hasHeightForWidth())
        self.addRimLight_pushButton.setSizePolicy(sizePolicy)
        self.addRimLight_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.addRimLight_pushButton.setFont(font)
        self.addRimLight_pushButton.setObjectName("addRimLight_pushButton")
        self.verticalLayout.addWidget(self.addRimLight_pushButton)
        self.fileTextureManager_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileTextureManager_pushButton.setObjectName("fileTextureManager_pushButton")
        self.verticalLayout.addWidget(self.fileTextureManager_pushButton)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.exportAlembic_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportAlembic_pushButton.sizePolicy().hasHeightForWidth())
        self.exportAlembic_pushButton.setSizePolicy(sizePolicy)
        self.exportAlembic_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.exportAlembic_pushButton.setFont(font)
        self.exportAlembic_pushButton.setObjectName("exportAlembic_pushButton")
        self.horizontalLayout_4.addWidget(self.exportAlembic_pushButton)
        self.importAlembic_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importAlembic_pushButton.sizePolicy().hasHeightForWidth())
        self.importAlembic_pushButton.setSizePolicy(sizePolicy)
        self.importAlembic_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.importAlembic_pushButton.setFont(font)
        self.importAlembic_pushButton.setObjectName("importAlembic_pushButton")
        self.horizontalLayout_4.addWidget(self.importAlembic_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.connectAlembic_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectAlembic_pushButton.sizePolicy().hasHeightForWidth())
        self.connectAlembic_pushButton.setSizePolicy(sizePolicy)
        self.connectAlembic_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.connectAlembic_pushButton.setFont(font)
        self.connectAlembic_pushButton.setObjectName("connectAlembic_pushButton")
        self.horizontalLayout_10.addWidget(self.connectAlembic_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_8.addWidget(self.line_7)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_8.addWidget(self.line_8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.arnoldLoad_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arnoldLoad_pushButton.sizePolicy().hasHeightForWidth())
        self.arnoldLoad_pushButton.setSizePolicy(sizePolicy)
        self.arnoldLoad_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldLoad_pushButton.setObjectName("arnoldLoad_pushButton")
        self.verticalLayout.addWidget(self.arnoldLoad_pushButton)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout.addWidget(self.line_12)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.arnoldAddProxyMat_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.arnoldAddProxyMat_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldAddProxyMat_pushButton.setObjectName("arnoldAddProxyMat_pushButton")
        self.horizontalLayout_2.addWidget(self.arnoldAddProxyMat_pushButton)
        self.arnoldDeleteProxyMat_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.arnoldDeleteProxyMat_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldDeleteProxyMat_pushButton.setObjectName("arnoldDeleteProxyMat_pushButton")
        self.horizontalLayout_2.addWidget(self.arnoldDeleteProxyMat_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.transferShading_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.transferShading_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.transferShading_pushButton.setObjectName("transferShading_pushButton")
        self.verticalLayout.addWidget(self.transferShading_pushButton)
        self.autoAsignShaders_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.autoAsignShaders_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.autoAsignShaders_pushButton.setObjectName("autoAsignShaders_pushButton")
        self.verticalLayout.addWidget(self.autoAsignShaders_pushButton)
        self.nMakeTx_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.nMakeTx_pushButton.setObjectName("nMakeTx_pushButton")
        self.verticalLayout.addWidget(self.nMakeTx_pushButton)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout.addWidget(self.line_10)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.leaveProxy_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.leaveProxy_checkBox.setObjectName("leaveProxy_checkBox")
        self.verticalLayout.addWidget(self.leaveProxy_checkBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.arnoldConvertToStandard_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.arnoldConvertToStandard_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldConvertToStandard_pushButton.setObjectName("arnoldConvertToStandard_pushButton")
        self.horizontalLayout.addWidget(self.arnoldConvertToStandard_pushButton)
        self.arnoldConvertToAlSurface_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.arnoldConvertToAlSurface_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldConvertToAlSurface_pushButton.setObjectName("arnoldConvertToAlSurface_pushButton")
        self.horizontalLayout.addWidget(self.arnoldConvertToAlSurface_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.arnoldIdLayer_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.arnoldIdLayer_spinBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.arnoldIdLayer_spinBox.setMinimum(1)
        self.arnoldIdLayer_spinBox.setObjectName("arnoldIdLayer_spinBox")
        self.gridLayout.addWidget(self.arnoldIdLayer_spinBox, 1, 5, 1, 1)
        self.idGreen_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.idGreen_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(8, 162, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 162, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.idGreen_pushButton.setPalette(palette)
        self.idGreen_pushButton.setObjectName("idGreen_pushButton")
        self.gridLayout.addWidget(self.idGreen_pushButton, 1, 2, 1, 1)
        self.idRed_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.idRed_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.idRed_pushButton.setPalette(palette)
        self.idRed_pushButton.setObjectName("idRed_pushButton")
        self.gridLayout.addWidget(self.idRed_pushButton, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 4, 1, 1)
        self.idBlue_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.idBlue_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 4, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 4, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.idBlue_pushButton.setPalette(palette)
        self.idBlue_pushButton.setObjectName("idBlue_pushButton")
        self.gridLayout.addWidget(self.idBlue_pushButton, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.arnoldAddObjID_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.arnoldAddObjID_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldAddObjID_pushButton.setObjectName("arnoldAddObjID_pushButton")
        self.horizontalLayout_11.addWidget(self.arnoldAddObjID_pushButton)
        self.arnoldRemObjID_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.arnoldRemObjID_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldRemObjID_pushButton.setObjectName("arnoldRemObjID_pushButton")
        self.horizontalLayout_11.addWidget(self.arnoldRemObjID_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.arnoldAddShaderID_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.arnoldAddShaderID_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldAddShaderID_pushButton.setObjectName("arnoldAddShaderID_pushButton")
        self.horizontalLayout_9.addWidget(self.arnoldAddShaderID_pushButton)
        self.arnoldRemShaderID_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.arnoldRemShaderID_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldRemShaderID_pushButton.setObjectName("arnoldRemShaderID_pushButton")
        self.horizontalLayout_9.addWidget(self.arnoldRemShaderID_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout.addWidget(self.line_11)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.arnoldSubdivision_none = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arnoldSubdivision_none.sizePolicy().hasHeightForWidth())
        self.arnoldSubdivision_none.setSizePolicy(sizePolicy)
        self.arnoldSubdivision_none.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.arnoldSubdivision_none.setFont(font)
        self.arnoldSubdivision_none.setObjectName("arnoldSubdivision_none")
        self.horizontalLayout_3.addWidget(self.arnoldSubdivision_none)
        self.arnoldSubdivision_catclark = QtWidgets.QPushButton(self.centralwidget)
        self.arnoldSubdivision_catclark.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldSubdivision_catclark.setObjectName("arnoldSubdivision_catclark")
        self.horizontalLayout_3.addWidget(self.arnoldSubdivision_catclark)
        self.arnoldSubdivision_linear = QtWidgets.QPushButton(self.centralwidget)
        self.arnoldSubdivision_linear.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldSubdivision_linear.setObjectName("arnoldSubdivision_linear")
        self.horizontalLayout_3.addWidget(self.arnoldSubdivision_linear)
        self.arnoldSubdivision_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arnoldSubdivision_spinBox.sizePolicy().hasHeightForWidth())
        self.arnoldSubdivision_spinBox.setSizePolicy(sizePolicy)
        self.arnoldSubdivision_spinBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.arnoldSubdivision_spinBox.setProperty("value", 2)
        self.arnoldSubdivision_spinBox.setObjectName("arnoldSubdivision_spinBox")
        self.horizontalLayout_3.addWidget(self.arnoldSubdivision_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.arnoldOpaque_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.arnoldOpaque_checkBox.setObjectName("arnoldOpaque_checkBox")
        self.horizontalLayout_12.addWidget(self.arnoldOpaque_checkBox)
        self.arnoldSelfShad_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.arnoldSelfShad_checkBox.setChecked(True)
        self.arnoldSelfShad_checkBox.setObjectName("arnoldSelfShad_checkBox")
        self.horizontalLayout_12.addWidget(self.arnoldSelfShad_checkBox)
        self.arnoldInDiff_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.arnoldInDiff_checkBox.setChecked(True)
        self.arnoldInDiff_checkBox.setObjectName("arnoldInDiff_checkBox")
        self.horizontalLayout_12.addWidget(self.arnoldInDiff_checkBox)
        self.arnoldInSpec_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.arnoldInSpec_checkBox.setChecked(True)
        self.arnoldInSpec_checkBox.setTristate(False)
        self.arnoldInSpec_checkBox.setObjectName("arnoldInSpec_checkBox")
        self.horizontalLayout_12.addWidget(self.arnoldInSpec_checkBox)
        self.arnoldMatte_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.arnoldMatte_checkBox.setObjectName("arnoldMatte_checkBox")
        self.horizontalLayout_12.addWidget(self.arnoldMatte_checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.arnoldAddAttrs_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.arnoldAddAttrs_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldAddAttrs_pushButton.setObjectName("arnoldAddAttrs_pushButton")
        self.verticalLayout.addWidget(self.arnoldAddAttrs_pushButton)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout.addWidget(self.line_9)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.alLightGroup_1_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_1_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_1_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_1_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_1_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_1_pushButton.setObjectName("alLightGroup_1_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_1_pushButton)
        self.alLightGroup_2_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_2_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_2_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_2_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_2_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_2_pushButton.setObjectName("alLightGroup_2_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_2_pushButton)
        self.alLightGroup_3_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_3_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_3_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_3_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_3_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_3_pushButton.setObjectName("alLightGroup_3_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_3_pushButton)
        self.alLightGroup_4_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_4_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_4_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_4_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_4_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_4_pushButton.setObjectName("alLightGroup_4_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_4_pushButton)
        self.alLightGroup_5_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_5_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_5_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_5_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_5_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_5_pushButton.setObjectName("alLightGroup_5_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_5_pushButton)
        self.alLightGroup_6_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_6_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_6_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_6_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_6_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_6_pushButton.setObjectName("alLightGroup_6_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_6_pushButton)
        self.alLightGroup_7_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_7_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_7_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_7_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_7_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_7_pushButton.setObjectName("alLightGroup_7_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_7_pushButton)
        self.alLightGroup_8_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_8_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_8_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_8_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_8_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_8_pushButton.setObjectName("alLightGroup_8_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_8_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tapp Lighting"))
        self.label_2.setText(_translate("MainWindow", "General"))
        self.addRimLight_pushButton.setText(_translate("MainWindow", "Add Rim Light"))
        self.fileTextureManager_pushButton.setText(_translate("MainWindow", "File Texture Manager"))
        self.label.setText(_translate("MainWindow", "Alembic"))
        self.exportAlembic_pushButton.setText(_translate("MainWindow", "Export Alembic"))
        self.importAlembic_pushButton.setText(_translate("MainWindow", "Import Alembic"))
        self.connectAlembic_pushButton.setText(_translate("MainWindow", "Connect Alembic"))
        self.label_4.setText(_translate("MainWindow", "Arnold"))
        self.arnoldLoad_pushButton.setText(_translate("MainWindow", "Load Arnold Renderer"))
        self.label_7.setText(_translate("MainWindow", "Materials"))
        self.arnoldAddProxyMat_pushButton.setText(_translate("MainWindow", "Add proxy mat"))
        self.arnoldDeleteProxyMat_pushButton.setText(_translate("MainWindow", "Delete proxy mat"))
        self.transferShading_pushButton.setText(_translate("MainWindow", "Transfer Shading"))
        self.autoAsignShaders_pushButton.setText(_translate("MainWindow", "Auto assign shaders"))
        self.nMakeTx_pushButton.setText(_translate("MainWindow", "arnold TX manager"))
        self.label_6.setText(_translate("MainWindow", "Convert material to"))
        self.leaveProxy_checkBox.setText(_translate("MainWindow", "Leave old material as proxy"))
        self.arnoldConvertToStandard_pushButton.setText(_translate("MainWindow", "aiStandard"))
        self.arnoldConvertToAlSurface_pushButton.setText(_translate("MainWindow", "alSurface"))
        self.label_5.setText(_translate("MainWindow", "IDs"))
        self.idGreen_pushButton.setText(_translate("MainWindow", "Green"))
        self.idRed_pushButton.setText(_translate("MainWindow", "Red"))
        self.label_9.setText(_translate("MainWindow", "Layer"))
        self.idBlue_pushButton.setText(_translate("MainWindow", "Blue"))
        self.arnoldAddObjID_pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Makes the selection into a AOV rgb mask.</p></body></html>"))
        self.arnoldAddObjID_pushButton.setText(_translate("MainWindow", "Object IDs from sets"))
        self.arnoldRemObjID_pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Rebuilds the AOV rgb mask from the current sets.</p></body></html>"))
        self.arnoldRemObjID_pushButton.setText(_translate("MainWindow", "Remove Object IDs"))
        self.arnoldAddShaderID_pushButton.setText(_translate("MainWindow", "Set Shader IDs"))
        self.arnoldRemShaderID_pushButton.setText(_translate("MainWindow", "Remove Shader IDs"))
        self.label_3.setText(_translate("MainWindow", "Subdivisions"))
        self.arnoldSubdivision_none.setText(_translate("MainWindow", "None"))
        self.arnoldSubdivision_catclark.setText(_translate("MainWindow", "Catclark"))
        self.arnoldSubdivision_linear.setText(_translate("MainWindow", "Linear"))
        self.label_11.setText(_translate("MainWindow", "OtherAttributes"))
        self.arnoldOpaque_checkBox.setText(_translate("MainWindow", "Opaque"))
        self.arnoldSelfShad_checkBox.setText(_translate("MainWindow", "Self Shad"))
        self.arnoldInDiff_checkBox.setText(_translate("MainWindow", "In Diff"))
        self.arnoldInSpec_checkBox.setText(_translate("MainWindow", "In Spec"))
        self.arnoldMatte_checkBox.setText(_translate("MainWindow", "Matte"))
        self.arnoldAddAttrs_pushButton.setText(_translate("MainWindow", "Add Arnold Attributes"))
        self.label_8.setText(_translate("MainWindow", "alSurface LightGroups"))
        self.alLightGroup_1_pushButton.setText(_translate("MainWindow", "1"))
        self.alLightGroup_2_pushButton.setText(_translate("MainWindow", "2"))
        self.alLightGroup_3_pushButton.setText(_translate("MainWindow", "3"))
        self.alLightGroup_4_pushButton.setText(_translate("MainWindow", "4"))
        self.alLightGroup_5_pushButton.setText(_translate("MainWindow", "5"))
        self.alLightGroup_6_pushButton.setText(_translate("MainWindow", "6"))
        self.alLightGroup_7_pushButton.setText(_translate("MainWindow", "7"))
        self.alLightGroup_8_pushButton.setText(_translate("MainWindow", "8"))
