# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created: Mon May 23 18:55:11 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(336, 886)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_3 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.addRimLight_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addRimLight_pushButton.sizePolicy().hasHeightForWidth())
        self.addRimLight_pushButton.setSizePolicy(sizePolicy)
        self.addRimLight_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.addRimLight_pushButton.setFont(font)
        self.addRimLight_pushButton.setObjectName("addRimLight_pushButton")
        self.verticalLayout.addWidget(self.addRimLight_pushButton)
        self.fileTextureManager_pushButton = QtGui.QPushButton(self.centralwidget)
        self.fileTextureManager_pushButton.setObjectName("fileTextureManager_pushButton")
        self.verticalLayout.addWidget(self.fileTextureManager_pushButton)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.exportAlembic_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportAlembic_pushButton.sizePolicy().hasHeightForWidth())
        self.exportAlembic_pushButton.setSizePolicy(sizePolicy)
        self.exportAlembic_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.exportAlembic_pushButton.setFont(font)
        self.exportAlembic_pushButton.setObjectName("exportAlembic_pushButton")
        self.horizontalLayout_4.addWidget(self.exportAlembic_pushButton)
        self.importAlembic_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importAlembic_pushButton.sizePolicy().hasHeightForWidth())
        self.importAlembic_pushButton.setSizePolicy(sizePolicy)
        self.importAlembic_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.importAlembic_pushButton.setFont(font)
        self.importAlembic_pushButton.setObjectName("importAlembic_pushButton")
        self.horizontalLayout_4.addWidget(self.importAlembic_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.connectAlembic_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectAlembic_pushButton.sizePolicy().hasHeightForWidth())
        self.connectAlembic_pushButton.setSizePolicy(sizePolicy)
        self.connectAlembic_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.connectAlembic_pushButton.setFont(font)
        self.connectAlembic_pushButton.setObjectName("connectAlembic_pushButton")
        self.horizontalLayout_10.addWidget(self.connectAlembic_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.line_7 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_8.addWidget(self.line_7)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_8.addWidget(self.line_8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.arnoldLoad_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arnoldLoad_pushButton.sizePolicy().hasHeightForWidth())
        self.arnoldLoad_pushButton.setSizePolicy(sizePolicy)
        self.arnoldLoad_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldLoad_pushButton.setObjectName("arnoldLoad_pushButton")
        self.verticalLayout.addWidget(self.arnoldLoad_pushButton)
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout.addWidget(self.line_12)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.arnoldAddProxyMat_pushButton = QtGui.QPushButton(self.centralwidget)
        self.arnoldAddProxyMat_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldAddProxyMat_pushButton.setObjectName("arnoldAddProxyMat_pushButton")
        self.horizontalLayout_2.addWidget(self.arnoldAddProxyMat_pushButton)
        self.arnoldDeleteProxyMat_pushButton = QtGui.QPushButton(self.centralwidget)
        self.arnoldDeleteProxyMat_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldDeleteProxyMat_pushButton.setObjectName("arnoldDeleteProxyMat_pushButton")
        self.horizontalLayout_2.addWidget(self.arnoldDeleteProxyMat_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.transferShading_pushButton = QtGui.QPushButton(self.centralwidget)
        self.transferShading_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.transferShading_pushButton.setObjectName("transferShading_pushButton")
        self.verticalLayout.addWidget(self.transferShading_pushButton)
        self.autoAsignShaders_pushButton = QtGui.QPushButton(self.centralwidget)
        self.autoAsignShaders_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.autoAsignShaders_pushButton.setObjectName("autoAsignShaders_pushButton")
        self.verticalLayout.addWidget(self.autoAsignShaders_pushButton)
        self.nMakeTx_pushButton = QtGui.QPushButton(self.centralwidget)
        self.nMakeTx_pushButton.setObjectName("nMakeTx_pushButton")
        self.verticalLayout.addWidget(self.nMakeTx_pushButton)
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout.addWidget(self.line_10)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.leaveProxy_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.leaveProxy_checkBox.setObjectName("leaveProxy_checkBox")
        self.verticalLayout.addWidget(self.leaveProxy_checkBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.arnoldConvertToStandard_pushButton = QtGui.QPushButton(self.centralwidget)
        self.arnoldConvertToStandard_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldConvertToStandard_pushButton.setObjectName("arnoldConvertToStandard_pushButton")
        self.horizontalLayout.addWidget(self.arnoldConvertToStandard_pushButton)
        self.arnoldConvertToAlSurface_pushButton = QtGui.QPushButton(self.centralwidget)
        self.arnoldConvertToAlSurface_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldConvertToAlSurface_pushButton.setObjectName("arnoldConvertToAlSurface_pushButton")
        self.horizontalLayout.addWidget(self.arnoldConvertToAlSurface_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.arnoldIdLayer_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.arnoldIdLayer_spinBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.arnoldIdLayer_spinBox.setMinimum(1)
        self.arnoldIdLayer_spinBox.setObjectName("arnoldIdLayer_spinBox")
        self.gridLayout.addWidget(self.arnoldIdLayer_spinBox, 1, 5, 1, 1)
        self.idGreen_pushButton = QtGui.QPushButton(self.centralwidget)
        self.idGreen_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(8, 162, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 162, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.idGreen_pushButton.setPalette(palette)
        self.idGreen_pushButton.setObjectName("idGreen_pushButton")
        self.gridLayout.addWidget(self.idGreen_pushButton, 1, 2, 1, 1)
        self.idRed_pushButton = QtGui.QPushButton(self.centralwidget)
        self.idRed_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.idRed_pushButton.setPalette(palette)
        self.idRed_pushButton.setObjectName("idRed_pushButton")
        self.gridLayout.addWidget(self.idRed_pushButton, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 4, 1, 1)
        self.idBlue_pushButton = QtGui.QPushButton(self.centralwidget)
        self.idBlue_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 4, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 4, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.idBlue_pushButton.setPalette(palette)
        self.idBlue_pushButton.setObjectName("idBlue_pushButton")
        self.gridLayout.addWidget(self.idBlue_pushButton, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.arnoldAddObjID_pushButton = QtGui.QPushButton(self.centralwidget)
        self.arnoldAddObjID_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldAddObjID_pushButton.setObjectName("arnoldAddObjID_pushButton")
        self.horizontalLayout_11.addWidget(self.arnoldAddObjID_pushButton)
        self.arnoldRemObjID_pushButton = QtGui.QPushButton(self.centralwidget)
        self.arnoldRemObjID_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldRemObjID_pushButton.setObjectName("arnoldRemObjID_pushButton")
        self.horizontalLayout_11.addWidget(self.arnoldRemObjID_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.arnoldAddShaderID_pushButton = QtGui.QPushButton(self.centralwidget)
        self.arnoldAddShaderID_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldAddShaderID_pushButton.setObjectName("arnoldAddShaderID_pushButton")
        self.horizontalLayout_9.addWidget(self.arnoldAddShaderID_pushButton)
        self.arnoldRemShaderID_pushButton = QtGui.QPushButton(self.centralwidget)
        self.arnoldRemShaderID_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldRemShaderID_pushButton.setObjectName("arnoldRemShaderID_pushButton")
        self.horizontalLayout_9.addWidget(self.arnoldRemShaderID_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout.addWidget(self.line_11)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.arnoldSubdivision_none = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arnoldSubdivision_none.sizePolicy().hasHeightForWidth())
        self.arnoldSubdivision_none.setSizePolicy(sizePolicy)
        self.arnoldSubdivision_none.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.arnoldSubdivision_none.setFont(font)
        self.arnoldSubdivision_none.setObjectName("arnoldSubdivision_none")
        self.horizontalLayout_3.addWidget(self.arnoldSubdivision_none)
        self.arnoldSubdivision_catclark = QtGui.QPushButton(self.centralwidget)
        self.arnoldSubdivision_catclark.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldSubdivision_catclark.setObjectName("arnoldSubdivision_catclark")
        self.horizontalLayout_3.addWidget(self.arnoldSubdivision_catclark)
        self.arnoldSubdivision_linear = QtGui.QPushButton(self.centralwidget)
        self.arnoldSubdivision_linear.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldSubdivision_linear.setObjectName("arnoldSubdivision_linear")
        self.horizontalLayout_3.addWidget(self.arnoldSubdivision_linear)
        self.arnoldSubdivision_spinBox = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arnoldSubdivision_spinBox.sizePolicy().hasHeightForWidth())
        self.arnoldSubdivision_spinBox.setSizePolicy(sizePolicy)
        self.arnoldSubdivision_spinBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.arnoldSubdivision_spinBox.setProperty("value", 2)
        self.arnoldSubdivision_spinBox.setObjectName("arnoldSubdivision_spinBox")
        self.horizontalLayout_3.addWidget(self.arnoldSubdivision_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.arnoldOpaque_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.arnoldOpaque_checkBox.setObjectName("arnoldOpaque_checkBox")
        self.horizontalLayout_12.addWidget(self.arnoldOpaque_checkBox)
        self.arnoldSelfShad_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.arnoldSelfShad_checkBox.setChecked(True)
        self.arnoldSelfShad_checkBox.setObjectName("arnoldSelfShad_checkBox")
        self.horizontalLayout_12.addWidget(self.arnoldSelfShad_checkBox)
        self.arnoldInDiff_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.arnoldInDiff_checkBox.setChecked(True)
        self.arnoldInDiff_checkBox.setObjectName("arnoldInDiff_checkBox")
        self.horizontalLayout_12.addWidget(self.arnoldInDiff_checkBox)
        self.arnoldInSpec_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.arnoldInSpec_checkBox.setChecked(True)
        self.arnoldInSpec_checkBox.setTristate(False)
        self.arnoldInSpec_checkBox.setObjectName("arnoldInSpec_checkBox")
        self.horizontalLayout_12.addWidget(self.arnoldInSpec_checkBox)
        self.arnoldMatte_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.arnoldMatte_checkBox.setObjectName("arnoldMatte_checkBox")
        self.horizontalLayout_12.addWidget(self.arnoldMatte_checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.arnoldAddAttrs_pushButton = QtGui.QPushButton(self.centralwidget)
        self.arnoldAddAttrs_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.arnoldAddAttrs_pushButton.setObjectName("arnoldAddAttrs_pushButton")
        self.verticalLayout.addWidget(self.arnoldAddAttrs_pushButton)
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout.addWidget(self.line_9)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.alLightGroup_1_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_1_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_1_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_1_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_1_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_1_pushButton.setObjectName("alLightGroup_1_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_1_pushButton)
        self.alLightGroup_2_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_2_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_2_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_2_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_2_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_2_pushButton.setObjectName("alLightGroup_2_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_2_pushButton)
        self.alLightGroup_3_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_3_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_3_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_3_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_3_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_3_pushButton.setObjectName("alLightGroup_3_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_3_pushButton)
        self.alLightGroup_4_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_4_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_4_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_4_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_4_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_4_pushButton.setObjectName("alLightGroup_4_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_4_pushButton)
        self.alLightGroup_5_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_5_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_5_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_5_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_5_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_5_pushButton.setObjectName("alLightGroup_5_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_5_pushButton)
        self.alLightGroup_6_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_6_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_6_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_6_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_6_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_6_pushButton.setObjectName("alLightGroup_6_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_6_pushButton)
        self.alLightGroup_7_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_7_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_7_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_7_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_7_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_7_pushButton.setObjectName("alLightGroup_7_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_7_pushButton)
        self.alLightGroup_8_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alLightGroup_8_pushButton.sizePolicy().hasHeightForWidth())
        self.alLightGroup_8_pushButton.setSizePolicy(sizePolicy)
        self.alLightGroup_8_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.alLightGroup_8_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.alLightGroup_8_pushButton.setObjectName("alLightGroup_8_pushButton")
        self.horizontalLayout_7.addWidget(self.alLightGroup_8_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tapp Lighting", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.addRimLight_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add Rim Light", None, QtGui.QApplication.UnicodeUTF8))
        self.fileTextureManager_pushButton.setText(QtGui.QApplication.translate("MainWindow", "File Texture Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Alembic", None, QtGui.QApplication.UnicodeUTF8))
        self.exportAlembic_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Export Alembic", None, QtGui.QApplication.UnicodeUTF8))
        self.importAlembic_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Import Alembic", None, QtGui.QApplication.UnicodeUTF8))
        self.connectAlembic_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Connect Alembic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Arnold", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldLoad_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Load Arnold Renderer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Materials", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldAddProxyMat_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add proxy mat", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldDeleteProxyMat_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Delete proxy mat", None, QtGui.QApplication.UnicodeUTF8))
        self.transferShading_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Transfer Shading", None, QtGui.QApplication.UnicodeUTF8))
        self.autoAsignShaders_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Auto assign shaders", None, QtGui.QApplication.UnicodeUTF8))
        self.nMakeTx_pushButton.setText(QtGui.QApplication.translate("MainWindow", "arnold TX manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Convert material to", None, QtGui.QApplication.UnicodeUTF8))
        self.leaveProxy_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Leave old material as proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldConvertToStandard_pushButton.setText(QtGui.QApplication.translate("MainWindow", "aiStandard", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldConvertToAlSurface_pushButton.setText(QtGui.QApplication.translate("MainWindow", "alSurface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "IDs", None, QtGui.QApplication.UnicodeUTF8))
        self.idGreen_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.idRed_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.idBlue_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldAddObjID_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Makes the selection into a AOV rgb mask.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldAddObjID_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Object IDs from sets", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldRemObjID_pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Rebuilds the AOV rgb mask from the current sets.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldRemObjID_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Remove Object IDs", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldAddShaderID_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Set Shader IDs", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldRemShaderID_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Remove Shader IDs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Subdivisions", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldSubdivision_none.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldSubdivision_catclark.setText(QtGui.QApplication.translate("MainWindow", "Catclark", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldSubdivision_linear.setText(QtGui.QApplication.translate("MainWindow", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "OtherAttributes", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldOpaque_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Opaque", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldSelfShad_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Self Shad", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldInDiff_checkBox.setText(QtGui.QApplication.translate("MainWindow", "In Diff", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldInSpec_checkBox.setText(QtGui.QApplication.translate("MainWindow", "In Spec", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldMatte_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Matte", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldAddAttrs_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Add Arnold Attributes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "alSurface LightGroups", None, QtGui.QApplication.UnicodeUTF8))
        self.alLightGroup_1_pushButton.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.alLightGroup_2_pushButton.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.alLightGroup_3_pushButton.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.alLightGroup_4_pushButton.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.alLightGroup_5_pushButton.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.alLightGroup_6_pushButton.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.alLightGroup_7_pushButton.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.alLightGroup_8_pushButton.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))

