# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:/.core/dev/tapp/Tapp/Maya/animation\character\resources\dialog.ui'
#
# Created: Mon Aug 15 18:32:32 2016
#      by: Qt UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(292, 466)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_23 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_23.sizePolicy().hasHeightForWidth())
        self.line_23.setSizePolicy(sizePolicy)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.horizontalLayout_2.addWidget(self.line_23)
        self.character_fkik_label = QtWidgets.QLabel(self.centralwidget)
        self.character_fkik_label.setObjectName("character_fkik_label")
        self.horizontalLayout_2.addWidget(self.character_fkik_label)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fk_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fk_pushButton.sizePolicy().hasHeightForWidth())
        self.fk_pushButton.setSizePolicy(sizePolicy)
        self.fk_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fk_pushButton.setFont(font)
        self.fk_pushButton.setObjectName("fk_pushButton")
        self.horizontalLayout.addWidget(self.fk_pushButton)
        self.ik_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ik_pushButton.sizePolicy().hasHeightForWidth())
        self.ik_pushButton.setSizePolicy(sizePolicy)
        self.ik_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ik_pushButton.setFont(font)
        self.ik_pushButton.setObjectName("ik_pushButton")
        self.horizontalLayout.addWidget(self.ik_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.range_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.range_checkBox.setObjectName("range_checkBox")
        self.horizontalLayout_26.addWidget(self.range_checkBox)
        self.getTimeline_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.getTimeline_pushButton.setObjectName("getTimeline_pushButton")
        self.horizontalLayout_26.addWidget(self.getTimeline_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_pushButton.setObjectName("start_pushButton")
        self.horizontalLayout_7.addWidget(self.start_pushButton)
        self.start_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.start_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.start_lineEdit.setObjectName("start_lineEdit")
        self.horizontalLayout_7.addWidget(self.start_lineEdit)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.end_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.end_pushButton.setObjectName("end_pushButton")
        self.horizontalLayout_13.addWidget(self.end_pushButton)
        self.end_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.end_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.end_lineEdit.setObjectName("end_lineEdit")
        self.horizontalLayout_13.addWidget(self.end_lineEdit)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Character"))
        self.character_fkik_label.setText(_translate("MainWindow", "FK - IK Switching"))
        self.fk_pushButton.setText(_translate("MainWindow", "FK"))
        self.ik_pushButton.setText(_translate("MainWindow", "IK"))
        self.range_checkBox.setText(_translate("MainWindow", "Range"))
        self.getTimeline_pushButton.setText(_translate("MainWindow", "Get Timeline Info"))
        self.start_pushButton.setText(_translate("MainWindow", "Start:"))
        self.end_pushButton.setText(_translate("MainWindow", "End:"))
