# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:/.core/dev/tapp/Tapp/Maya/animation\tools\resources\dialog.ui'
#
# Created: Mon Aug 15 18:32:33 2016
#      by: Qt UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(272, 357)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.channelBoxLeft_horizontalLayout = QtWidgets.QHBoxLayout()
        self.channelBoxLeft_horizontalLayout.setObjectName("channelBoxLeft_horizontalLayout")
        self.horizontalLayout_3.addLayout(self.channelBoxLeft_horizontalLayout)
        self.central_verticalLayout = QtWidgets.QVBoxLayout()
        self.central_verticalLayout.setObjectName("central_verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.channelBoxLeft_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.channelBoxLeft_pushButton.setCheckable(True)
        self.channelBoxLeft_pushButton.setObjectName("channelBoxLeft_pushButton")
        self.horizontalLayout_2.addWidget(self.channelBoxLeft_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.channelBoxRight_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.channelBoxRight_pushButton.setCheckable(True)
        self.channelBoxRight_pushButton.setObjectName("channelBoxRight_pushButton")
        self.horizontalLayout_2.addWidget(self.channelBoxRight_pushButton)
        self.central_verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.zvParentMaster_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.zvParentMaster_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.zvParentMaster_pushButton.setObjectName("zvParentMaster_pushButton")
        self.horizontalLayout.addWidget(self.zvParentMaster_pushButton)
        self.zvChain_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.zvChain_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.zvChain_pushButton.setObjectName("zvChain_pushButton")
        self.horizontalLayout.addWidget(self.zvChain_pushButton)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout.addWidget(self.line_9)
        self.zvParentMasterHelp_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zvParentMasterHelp_pushButton.sizePolicy().hasHeightForWidth())
        self.zvParentMasterHelp_pushButton.setSizePolicy(sizePolicy)
        self.zvParentMasterHelp_pushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.zvParentMasterHelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.zvParentMasterHelp_pushButton.setObjectName("zvParentMasterHelp_pushButton")
        self.horizontalLayout.addWidget(self.zvParentMasterHelp_pushButton)
        self.central_verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.breakDownDragger_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.breakDownDragger_pushButton.sizePolicy().hasHeightForWidth())
        self.breakDownDragger_pushButton.setSizePolicy(sizePolicy)
        self.breakDownDragger_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.breakDownDragger_pushButton.setObjectName("breakDownDragger_pushButton")
        self.horizontalLayout_18.addWidget(self.breakDownDragger_pushButton)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_18.addWidget(self.line_11)
        self.breakDownDraggerHelp_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.breakDownDraggerHelp_pushButton.sizePolicy().hasHeightForWidth())
        self.breakDownDraggerHelp_pushButton.setSizePolicy(sizePolicy)
        self.breakDownDraggerHelp_pushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.breakDownDraggerHelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.breakDownDraggerHelp_pushButton.setObjectName("breakDownDraggerHelp_pushButton")
        self.horizontalLayout_18.addWidget(self.breakDownDraggerHelp_pushButton)
        self.central_verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.holdKey_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.holdKey_pushButton.sizePolicy().hasHeightForWidth())
        self.holdKey_pushButton.setSizePolicy(sizePolicy)
        self.holdKey_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.holdKey_pushButton.setObjectName("holdKey_pushButton")
        self.horizontalLayout_19.addWidget(self.holdKey_pushButton)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_19.addWidget(self.line_12)
        self.holdKeyHelp_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.holdKeyHelp_pushButton.sizePolicy().hasHeightForWidth())
        self.holdKeyHelp_pushButton.setSizePolicy(sizePolicy)
        self.holdKeyHelp_pushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.holdKeyHelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.holdKeyHelp_pushButton.setObjectName("holdKeyHelp_pushButton")
        self.horizontalLayout_19.addWidget(self.holdKeyHelp_pushButton)
        self.central_verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.keyValueDragger_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyValueDragger_pushButton.sizePolicy().hasHeightForWidth())
        self.keyValueDragger_pushButton.setSizePolicy(sizePolicy)
        self.keyValueDragger_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.keyValueDragger_pushButton.setObjectName("keyValueDragger_pushButton")
        self.horizontalLayout_20.addWidget(self.keyValueDragger_pushButton)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_20.addWidget(self.line_13)
        self.keyValueDraggerHelp_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyValueDraggerHelp_pushButton.sizePolicy().hasHeightForWidth())
        self.keyValueDraggerHelp_pushButton.setSizePolicy(sizePolicy)
        self.keyValueDraggerHelp_pushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.keyValueDraggerHelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.keyValueDraggerHelp_pushButton.setObjectName("keyValueDraggerHelp_pushButton")
        self.horizontalLayout_20.addWidget(self.keyValueDraggerHelp_pushButton)
        self.central_verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.keyCleanUp_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyCleanUp_pushButton.sizePolicy().hasHeightForWidth())
        self.keyCleanUp_pushButton.setSizePolicy(sizePolicy)
        self.keyCleanUp_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.keyCleanUp_pushButton.setObjectName("keyCleanUp_pushButton")
        self.horizontalLayout_17.addWidget(self.keyCleanUp_pushButton)
        self.line_25 = QtWidgets.QFrame(self.centralwidget)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.horizontalLayout_17.addWidget(self.line_25)
        self.keyCleanUpHelp_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.keyCleanUpHelp_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyCleanUpHelp_pushButton.sizePolicy().hasHeightForWidth())
        self.keyCleanUpHelp_pushButton.setSizePolicy(sizePolicy)
        self.keyCleanUpHelp_pushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.keyCleanUpHelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.keyCleanUpHelp_pushButton.setObjectName("keyCleanUpHelp_pushButton")
        self.horizontalLayout_17.addWidget(self.keyCleanUpHelp_pushButton)
        self.central_verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.changeRotationOrder_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changeRotationOrder_pushButton.sizePolicy().hasHeightForWidth())
        self.changeRotationOrder_pushButton.setSizePolicy(sizePolicy)
        self.changeRotationOrder_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.changeRotationOrder_pushButton.setObjectName("changeRotationOrder_pushButton")
        self.horizontalLayout_21.addWidget(self.changeRotationOrder_pushButton)
        self.changeRotationOrder_comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changeRotationOrder_comboBox.sizePolicy().hasHeightForWidth())
        self.changeRotationOrder_comboBox.setSizePolicy(sizePolicy)
        self.changeRotationOrder_comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.changeRotationOrder_comboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.changeRotationOrder_comboBox.setObjectName("changeRotationOrder_comboBox")
        self.changeRotationOrder_comboBox.addItem("")
        self.changeRotationOrder_comboBox.addItem("")
        self.changeRotationOrder_comboBox.addItem("")
        self.changeRotationOrder_comboBox.addItem("")
        self.changeRotationOrder_comboBox.addItem("")
        self.changeRotationOrder_comboBox.addItem("")
        self.horizontalLayout_21.addWidget(self.changeRotationOrder_comboBox)
        self.line_26 = QtWidgets.QFrame(self.centralwidget)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.horizontalLayout_21.addWidget(self.line_26)
        self.changeRotationOrderHelp_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.changeRotationOrderHelp_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changeRotationOrderHelp_pushButton.sizePolicy().hasHeightForWidth())
        self.changeRotationOrderHelp_pushButton.setSizePolicy(sizePolicy)
        self.changeRotationOrderHelp_pushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.changeRotationOrderHelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.changeRotationOrderHelp_pushButton.setObjectName("changeRotationOrderHelp_pushButton")
        self.horizontalLayout_21.addWidget(self.changeRotationOrderHelp_pushButton)
        self.central_verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.ghosting_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ghosting_pushButton.sizePolicy().hasHeightForWidth())
        self.ghosting_pushButton.setSizePolicy(sizePolicy)
        self.ghosting_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.ghosting_pushButton.setObjectName("ghosting_pushButton")
        self.horizontalLayout_23.addWidget(self.ghosting_pushButton)
        self.line_27 = QtWidgets.QFrame(self.centralwidget)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.horizontalLayout_23.addWidget(self.line_27)
        self.ghostingHelp_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ghostingHelp_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ghostingHelp_pushButton.sizePolicy().hasHeightForWidth())
        self.ghostingHelp_pushButton.setSizePolicy(sizePolicy)
        self.ghostingHelp_pushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.ghostingHelp_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.ghostingHelp_pushButton.setObjectName("ghostingHelp_pushButton")
        self.horizontalLayout_23.addWidget(self.ghostingHelp_pushButton)
        self.central_verticalLayout.addLayout(self.horizontalLayout_23)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.localizeImagePlane_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localizeImagePlane_pushButton.sizePolicy().hasHeightForWidth())
        self.localizeImagePlane_pushButton.setSizePolicy(sizePolicy)
        self.localizeImagePlane_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.localizeImagePlane_pushButton.setObjectName("localizeImagePlane_pushButton")
        self.gridLayout.addWidget(self.localizeImagePlane_pushButton, 0, 0, 1, 2)
        self.paie_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paie_pushButton.sizePolicy().hasHeightForWidth())
        self.paie_pushButton.setSizePolicy(sizePolicy)
        self.paie_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.paie_pushButton.setObjectName("paie_pushButton")
        self.gridLayout.addWidget(self.paie_pushButton, 1, 1, 1, 2)
        self.rat_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rat_pushButton.sizePolicy().hasHeightForWidth())
        self.rat_pushButton.setSizePolicy(sizePolicy)
        self.rat_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.rat_pushButton.setObjectName("rat_pushButton")
        self.gridLayout.addWidget(self.rat_pushButton, 0, 2, 1, 1)
        self.collisionDeformer_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.collisionDeformer_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.collisionDeformer_pushButton.setObjectName("collisionDeformer_pushButton")
        self.gridLayout.addWidget(self.collisionDeformer_pushButton, 1, 0, 1, 1)
        self.central_verticalLayout.addLayout(self.gridLayout)
        self.playblastQueue_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.playblastQueue_pushButton.setObjectName("playblastQueue_pushButton")
        self.central_verticalLayout.addWidget(self.playblastQueue_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.central_verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.central_verticalLayout)
        self.channelBoxRight_horizontalLayout = QtWidgets.QHBoxLayout()
        self.channelBoxRight_horizontalLayout.setObjectName("channelBoxRight_horizontalLayout")
        self.horizontalLayout_3.addLayout(self.channelBoxRight_horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tools"))
        self.channelBoxLeft_pushButton.setText(_translate("MainWindow", "<<<"))
        self.label.setText(_translate("MainWindow", "Channel Box"))
        self.channelBoxRight_pushButton.setText(_translate("MainWindow", ">>>"))
        self.zvParentMaster_pushButton.setText(_translate("MainWindow", "Zv Parent Master"))
        self.zvChain_pushButton.setText(_translate("MainWindow", "Zv Chain"))
        self.zvParentMasterHelp_pushButton.setText(_translate("MainWindow", "?"))
        self.breakDownDragger_pushButton.setText(_translate("MainWindow", "Breakdown Dragger"))
        self.breakDownDraggerHelp_pushButton.setText(_translate("MainWindow", "?"))
        self.holdKey_pushButton.setText(_translate("MainWindow", "Hold Key"))
        self.holdKeyHelp_pushButton.setText(_translate("MainWindow", "?"))
        self.keyValueDragger_pushButton.setText(_translate("MainWindow", "Key Value Dragger"))
        self.keyValueDraggerHelp_pushButton.setText(_translate("MainWindow", "?"))
        self.keyCleanUp_pushButton.setText(_translate("MainWindow", "Key Clean Up"))
        self.keyCleanUpHelp_pushButton.setText(_translate("MainWindow", "?"))
        self.changeRotationOrder_pushButton.setText(_translate("MainWindow", "Change Rotation Order"))
        self.changeRotationOrder_comboBox.setItemText(0, _translate("MainWindow", "xyz"))
        self.changeRotationOrder_comboBox.setItemText(1, _translate("MainWindow", "yzx"))
        self.changeRotationOrder_comboBox.setItemText(2, _translate("MainWindow", "zxy"))
        self.changeRotationOrder_comboBox.setItemText(3, _translate("MainWindow", "xzy"))
        self.changeRotationOrder_comboBox.setItemText(4, _translate("MainWindow", "yxz"))
        self.changeRotationOrder_comboBox.setItemText(5, _translate("MainWindow", "zyx"))
        self.changeRotationOrderHelp_pushButton.setText(_translate("MainWindow", "?"))
        self.ghosting_pushButton.setText(_translate("MainWindow", "Ghosting"))
        self.ghostingHelp_pushButton.setText(_translate("MainWindow", "?"))
        self.localizeImagePlane_pushButton.setText(_translate("MainWindow", "Localize Image Plane"))
        self.paie_pushButton.setText(_translate("MainWindow", "PAIE"))
        self.rat_pushButton.setText(_translate("MainWindow", "RAT"))
        self.collisionDeformer_pushButton.setText(_translate("MainWindow", "Collision Deformer"))
        self.playblastQueue_pushButton.setText(_translate("MainWindow", "Playblast Queue"))
