# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:/.core/dev/tapp/Tapp/Maya/settings\gui\resources\settings_gui.ui'
#
# Created: Mon Aug 15 18:32:33 2016
#      by: Qt UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtGui, QtWidgets

class Ui_tappSettings_MainWindow(object):
    def setupUi(self, tappSettings_MainWindow):
        tappSettings_MainWindow.setObjectName("tappSettings_MainWindow")
        tappSettings_MainWindow.resize(224, 213)
        self.centralwidget = QtWidgets.QWidget(tappSettings_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_7.addWidget(self.line_5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_7.addWidget(self.line_6)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.launchWindowAtStartup_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.launchWindowAtStartup_checkBox.setObjectName("launchWindowAtStartup_checkBox")
        self.verticalLayout.addWidget(self.launchWindowAtStartup_checkBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.repository_label = QtWidgets.QLabel(self.centralwidget)
        self.repository_label.setObjectName("repository_label")
        self.verticalLayout.addWidget(self.repository_label)
        self.setRepository_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setRepository_pushButton.sizePolicy().hasHeightForWidth())
        self.setRepository_pushButton.setSizePolicy(sizePolicy)
        self.setRepository_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.setRepository_pushButton.setFont(font)
        self.setRepository_pushButton.setObjectName("setRepository_pushButton")
        self.verticalLayout.addWidget(self.setRepository_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.saveSettings_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSettings_pushButton.sizePolicy().hasHeightForWidth())
        self.saveSettings_pushButton.setSizePolicy(sizePolicy)
        self.saveSettings_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.saveSettings_pushButton.setFont(font)
        self.saveSettings_pushButton.setObjectName("saveSettings_pushButton")
        self.verticalLayout.addWidget(self.saveSettings_pushButton)
        tappSettings_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(tappSettings_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(tappSettings_MainWindow)

    def retranslateUi(self, tappSettings_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        tappSettings_MainWindow.setWindowTitle(_translate("tappSettings_MainWindow", "Tapp Settings"))
        self.label_3.setText(_translate("tappSettings_MainWindow", "General"))
        self.launchWindowAtStartup_checkBox.setText(_translate("tappSettings_MainWindow", "Launch Tapp Window at startup"))
        self.label_2.setText(_translate("tappSettings_MainWindow", "Repository"))
        self.repository_label.setText(_translate("tappSettings_MainWindow", "Repository NOT read!"))
        self.setRepository_pushButton.setText(_translate("tappSettings_MainWindow", "Set Repository"))
        self.saveSettings_pushButton.setText(_translate("tappSettings_MainWindow", "Save Settings"))
