# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:/.core/dev/tapp/Tapp/Maya/animation\utils\RAT_ui.ui'
#
# Created: Mon Aug 15 18:32:33 2016
#      by: Qt UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtGui, QtWidgets

class Ui_RAT_mWindow(object):
    def setupUi(self, RAT_mWindow):
        RAT_mWindow.setObjectName("RAT_mWindow")
        RAT_mWindow.setEnabled(True)
        RAT_mWindow.resize(382, 760)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RAT_mWindow.sizePolicy().hasHeightForWidth())
        RAT_mWindow.setSizePolicy(sizePolicy)
        RAT_mWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        RAT_mWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(RAT_mWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.General_keyBreakdown_gBox = QtWidgets.QGroupBox(self.centralwidget)
        self.General_keyBreakdown_gBox.setGeometry(QtCore.QRect(9, 9, 364, 111))
        self.General_keyBreakdown_gBox.setMinimumSize(QtCore.QSize(100, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.General_keyBreakdown_gBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.General_keyBreakdown_gBox.setFont(font)
        self.General_keyBreakdown_gBox.setFlat(False)
        self.General_keyBreakdown_gBox.setCheckable(False)
        self.General_keyBreakdown_gBox.setObjectName("General_keyBreakdown_gBox")
        self.keyOnMinusThree_button = QtWidgets.QPushButton(self.General_keyBreakdown_gBox)
        self.keyOnMinusThree_button.setGeometry(QtCore.QRect(40, 19, 36, 33))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.keyOnMinusThree_button.setPalette(palette)
        self.keyOnMinusThree_button.setObjectName("keyOnMinusThree_button")
        self.keyOnMinusTwo_button = QtWidgets.QPushButton(self.General_keyBreakdown_gBox)
        self.keyOnMinusTwo_button.setGeometry(QtCore.QRect(80, 19, 31, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.keyOnMinusTwo_button.setPalette(palette)
        self.keyOnMinusTwo_button.setObjectName("keyOnMinusTwo_button")
        self.key0_button = QtWidgets.QPushButton(self.General_keyBreakdown_gBox)
        self.key0_button.setGeometry(QtCore.QRect(150, 15, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.key0_button.setPalette(palette)
        self.key0_button.setObjectName("key0_button")
        self.keyOnPlusTwo_button = QtWidgets.QPushButton(self.General_keyBreakdown_gBox)
        self.keyOnPlusTwo_button.setGeometry(QtCore.QRect(240, 19, 31, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.keyOnPlusTwo_button.setPalette(palette)
        self.keyOnPlusTwo_button.setObjectName("keyOnPlusTwo_button")
        self.keyOnPlusThree_button = QtWidgets.QPushButton(self.General_keyBreakdown_gBox)
        self.keyOnPlusThree_button.setGeometry(QtCore.QRect(275, 19, 36, 33))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.keyOnPlusThree_button.setPalette(palette)
        self.keyOnPlusThree_button.setObjectName("keyOnPlusThree_button")
        self.keyOnMinusOne_button = QtWidgets.QPushButton(self.General_keyBreakdown_gBox)
        self.keyOnMinusOne_button.setGeometry(QtCore.QRect(115, 17, 31, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.keyOnMinusOne_button.setPalette(palette)
        self.keyOnMinusOne_button.setObjectName("keyOnMinusOne_button")
        self.keyOnPlusOne_button = QtWidgets.QPushButton(self.General_keyBreakdown_gBox)
        self.keyOnPlusOne_button.setGeometry(QtCore.QRect(205, 17, 31, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.keyOnPlusOne_button.setPalette(palette)
        self.keyOnPlusOne_button.setObjectName("keyOnPlusOne_button")
        self.keyBreakdown_intSlider = QtWidgets.QSlider(self.General_keyBreakdown_gBox)
        self.keyBreakdown_intSlider.setGeometry(QtCore.QRect(55, 78, 246, 20))
        self.keyBreakdown_intSlider.setMinimum(-150)
        self.keyBreakdown_intSlider.setMaximum(150)
        self.keyBreakdown_intSlider.setSingleStep(1)
        self.keyBreakdown_intSlider.setPageStep(10)
        self.keyBreakdown_intSlider.setProperty("value", 0)
        self.keyBreakdown_intSlider.setSliderPosition(0)
        self.keyBreakdown_intSlider.setOrientation(QtCore.Qt.Horizontal)
        self.keyBreakdown_intSlider.setInvertedAppearance(False)
        self.keyBreakdown_intSlider.setInvertedControls(False)
        self.keyBreakdown_intSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.keyBreakdown_intSlider.setTickInterval(25)
        self.keyBreakdown_intSlider.setObjectName("keyBreakdown_intSlider")
        self.label_16 = QtWidgets.QLabel(self.General_keyBreakdown_gBox)
        self.label_16.setGeometry(QtCore.QRect(196, 55, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.keyBreakdown_tField = QtWidgets.QLineEdit(self.General_keyBreakdown_gBox)
        self.keyBreakdown_tField.setEnabled(True)
        self.keyBreakdown_tField.setGeometry(QtCore.QRect(156, 54, 41, 21))
        self.keyBreakdown_tField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.keyBreakdown_tField.setObjectName("keyBreakdown_tField")
        self.keyOnMinusThree_button_2 = QtWidgets.QPushButton(self.General_keyBreakdown_gBox)
        self.keyOnMinusThree_button_2.setGeometry(QtCore.QRect(5, 68, 46, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.keyOnMinusThree_button_2.setPalette(palette)
        self.keyOnMinusThree_button_2.setObjectName("keyOnMinusThree_button_2")
        self.keyOnMinusThree_button_3 = QtWidgets.QPushButton(self.General_keyBreakdown_gBox)
        self.keyOnMinusThree_button_3.setGeometry(QtCore.QRect(305, 68, 41, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.keyOnMinusThree_button_3.setPalette(palette)
        self.keyOnMinusThree_button_3.setObjectName("keyOnMinusThree_button_3")
        self.keyOnMinusThree_button_4 = QtWidgets.QPushButton(self.General_keyBreakdown_gBox)
        self.keyOnMinusThree_button_4.setGeometry(QtCore.QRect(315, 19, 31, 43))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.keyOnMinusThree_button_4.setPalette(palette)
        self.keyOnMinusThree_button_4.setObjectName("keyOnMinusThree_button_4")
        self.keyOnMinusThree_button_5 = QtWidgets.QPushButton(self.General_keyBreakdown_gBox)
        self.keyOnMinusThree_button_5.setGeometry(QtCore.QRect(5, 19, 31, 43))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.keyOnMinusThree_button_5.setPalette(palette)
        self.keyOnMinusThree_button_5.setObjectName("keyOnMinusThree_button_5")
        self.keyBreakdown_spinBox = QtWidgets.QSpinBox(self.General_keyBreakdown_gBox)
        self.keyBreakdown_spinBox.setGeometry(QtCore.QRect(220, 55, 42, 22))
        self.keyBreakdown_spinBox.setMinimum(-150)
        self.keyBreakdown_spinBox.setMaximum(150)
        self.keyBreakdown_spinBox.setObjectName("keyBreakdown_spinBox")
        self.Advanced_curveCleaner_gBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Advanced_curveCleaner_gBox.setGeometry(QtCore.QRect(10, 400, 364, 241))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.Advanced_curveCleaner_gBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Advanced_curveCleaner_gBox.setFont(font)
        self.Advanced_curveCleaner_gBox.setFlat(False)
        self.Advanced_curveCleaner_gBox.setCheckable(False)
        self.Advanced_curveCleaner_gBox.setObjectName("Advanced_curveCleaner_gBox")
        self.cleanCurves_button = QtWidgets.QPushButton(self.Advanced_curveCleaner_gBox)
        self.cleanCurves_button.setEnabled(False)
        self.cleanCurves_button.setGeometry(QtCore.QRect(10, 20, 181, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.cleanCurves_button.setPalette(palette)
        self.cleanCurves_button.setCheckable(False)
        self.cleanCurves_button.setObjectName("cleanCurves_button")
        self.flipCurves_button = QtWidgets.QPushButton(self.Advanced_curveCleaner_gBox)
        self.flipCurves_button.setGeometry(QtCore.QRect(10, 51, 211, 26))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.flipCurves_button.setPalette(palette)
        self.flipCurves_button.setObjectName("flipCurves_button")
        self.flipCurves_oMenu = QtWidgets.QComboBox(self.Advanced_curveCleaner_gBox)
        self.flipCurves_oMenu.setGeometry(QtCore.QRect(230, 53, 87, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.flipCurves_oMenu.setPalette(palette)
        self.flipCurves_oMenu.setObjectName("flipCurves_oMenu")
        self.flipCurves_oMenu.addItem("")
        self.flipCurves_oMenu.addItem("")
        self.flipCurves_oMenu.addItem("")
        self.flipCurves_oMenu.addItem("")
        self.snapAnimation_button = QtWidgets.QPushButton(self.Advanced_curveCleaner_gBox)
        self.snapAnimation_button.setGeometry(QtCore.QRect(10, 81, 211, 26))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.snapAnimation_button.setPalette(palette)
        self.snapAnimation_button.setObjectName("snapAnimation_button")
        self.snapAnimPivot_oMenu = QtWidgets.QComboBox(self.Advanced_curveCleaner_gBox)
        self.snapAnimPivot_oMenu.setGeometry(QtCore.QRect(230, 83, 49, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.snapAnimPivot_oMenu.setPalette(palette)
        self.snapAnimPivot_oMenu.setObjectName("snapAnimPivot_oMenu")
        self.snapAnimPivot_oMenu.addItem("")
        self.snapAnimPivot_oMenu.addItem("")
        self.softness_label = QtWidgets.QLabel(self.Advanced_curveCleaner_gBox)
        self.softness_label.setGeometry(QtCore.QRect(10, 210, 61, 21))
        self.softness_label.setObjectName("softness_label")
        self.curveSoftness_intSlider = QtWidgets.QSlider(self.Advanced_curveCleaner_gBox)
        self.curveSoftness_intSlider.setGeometry(QtCore.QRect(115, 210, 181, 21))
        self.curveSoftness_intSlider.setMaximum(1000)
        self.curveSoftness_intSlider.setSingleStep(2)
        self.curveSoftness_intSlider.setPageStep(100)
        self.curveSoftness_intSlider.setOrientation(QtCore.Qt.Horizontal)
        self.curveSoftness_intSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.curveSoftness_intSlider.setTickInterval(100)
        self.curveSoftness_intSlider.setObjectName("curveSoftness_intSlider")
        self.flatStartEnd_cBox = QtWidgets.QCheckBox(self.Advanced_curveCleaner_gBox)
        self.flatStartEnd_cBox.setGeometry(QtCore.QRect(10, 190, 151, 21))
        self.flatStartEnd_cBox.setObjectName("flatStartEnd_cBox")
        self.curveSoftness_tField = QtWidgets.QLineEdit(self.Advanced_curveCleaner_gBox)
        self.curveSoftness_tField.setGeometry(QtCore.QRect(70, 210, 36, 21))
        self.curveSoftness_tField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.curveSoftness_tField.setObjectName("curveSoftness_tField")
        self.autoTangent_button = QtWidgets.QPushButton(self.Advanced_curveCleaner_gBox)
        self.autoTangent_button.setGeometry(QtCore.QRect(305, 200, 36, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.autoTangent_button.setPalette(palette)
        self.autoTangent_button.setObjectName("autoTangent_button")
        self.cleanCurves_tField = QtWidgets.QLineEdit(self.Advanced_curveCleaner_gBox)
        self.cleanCurves_tField.setGeometry(QtCore.QRect(330, 55, 16, 20))
        self.cleanCurves_tField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cleanCurves_tField.setObjectName("cleanCurves_tField")
        self.label = QtWidgets.QLabel(self.Advanced_curveCleaner_gBox)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(215, 25, 71, 16))
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Advanced_curveCleaner_gBox)
        self.doubleSpinBox.setEnabled(False)
        self.doubleSpinBox.setGeometry(QtCore.QRect(280, 20, 62, 22))
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMinimum(0.001)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.002)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.cac_modifyValue_grp = QtWidgets.QGroupBox(self.Advanced_curveCleaner_gBox)
        self.cac_modifyValue_grp.setGeometry(QtCore.QRect(130, 110, 101, 81))
        self.cac_modifyValue_grp.setFlat(True)
        self.cac_modifyValue_grp.setCheckable(False)
        self.cac_modifyValue_grp.setObjectName("cac_modifyValue_grp")
        self.cac_v_01_button = QtWidgets.QRadioButton(self.cac_modifyValue_grp)
        self.cac_v_01_button.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.cac_v_01_button.setChecked(True)
        self.cac_v_01_button.setObjectName("cac_v_01_button")
        self.cac_v_02_button = QtWidgets.QRadioButton(self.cac_modifyValue_grp)
        self.cac_v_02_button.setGeometry(QtCore.QRect(10, 40, 101, 17))
        self.cac_v_02_button.setObjectName("cac_v_02_button")
        self.cac_v_03_button = QtWidgets.QRadioButton(self.cac_modifyValue_grp)
        self.cac_v_03_button.setGeometry(QtCore.QRect(10, 60, 71, 17))
        self.cac_v_03_button.setObjectName("cac_v_03_button")
        self.cac_modifyTangent_grp = QtWidgets.QGroupBox(self.Advanced_curveCleaner_gBox)
        self.cac_modifyTangent_grp.setGeometry(QtCore.QRect(240, 110, 101, 81))
        self.cac_modifyTangent_grp.setFlat(True)
        self.cac_modifyTangent_grp.setCheckable(False)
        self.cac_modifyTangent_grp.setObjectName("cac_modifyTangent_grp")
        self.cac_t_01_button = QtWidgets.QRadioButton(self.cac_modifyTangent_grp)
        self.cac_t_01_button.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.cac_t_01_button.setChecked(True)
        self.cac_t_01_button.setObjectName("cac_t_01_button")
        self.cac_t_02_button = QtWidgets.QRadioButton(self.cac_modifyTangent_grp)
        self.cac_t_02_button.setGeometry(QtCore.QRect(10, 40, 91, 17))
        self.cac_t_02_button.setObjectName("cac_t_02_button")
        self.cac_t_03_button = QtWidgets.QRadioButton(self.cac_modifyTangent_grp)
        self.cac_t_03_button.setGeometry(QtCore.QRect(10, 60, 71, 17))
        self.cac_t_03_button.setObjectName("cac_t_03_button")
        self.cycle_anim_curve_button = QtWidgets.QPushButton(self.Advanced_curveCleaner_gBox)
        self.cycle_anim_curve_button.setGeometry(QtCore.QRect(10, 150, 111, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.cycle_anim_curve_button.setPalette(palette)
        self.cycle_anim_curve_button.setObjectName("cycle_anim_curve_button")
        self.label_2 = QtWidgets.QLabel(self.Advanced_curveCleaner_gBox)
        self.label_2.setGeometry(QtCore.QRect(10, 115, 111, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.Advanced_curveCleaner_gBox)
        self.label_4.setGeometry(QtCore.QRect(40, 131, 61, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.cac_modifyValue = QtWidgets.QCheckBox(self.Advanced_curveCleaner_gBox)
        self.cac_modifyValue.setGeometry(QtCore.QRect(134, 110, 16, 18))
        self.cac_modifyValue.setText("")
        self.cac_modifyValue.setChecked(True)
        self.cac_modifyValue.setObjectName("cac_modifyValue")
        self.cac_modifyTangent = QtWidgets.QCheckBox(self.Advanced_curveCleaner_gBox)
        self.cac_modifyTangent.setGeometry(QtCore.QRect(244, 110, 16, 18))
        self.cac_modifyTangent.setText("")
        self.cac_modifyTangent.setChecked(True)
        self.cac_modifyTangent.setObjectName("cac_modifyTangent")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 640, 364, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.groupBox_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.camVerShift_intSlider = QtWidgets.QSlider(self.groupBox_3)
        self.camVerShift_intSlider.setGeometry(QtCore.QRect(76, 24, 253, 20))
        self.camVerShift_intSlider.setMinimum(-100)
        self.camVerShift_intSlider.setMaximum(100)
        self.camVerShift_intSlider.setOrientation(QtCore.Qt.Horizontal)
        self.camVerShift_intSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.camVerShift_intSlider.setObjectName("camVerShift_intSlider")
        self.resetCamera_button = QtWidgets.QPushButton(self.groupBox_3)
        self.resetCamera_button.setGeometry(QtCore.QRect(160, 73, 181, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.resetCamera_button.setPalette(palette)
        self.resetCamera_button.setObjectName("resetCamera_button")
        self.camHorShift_intSlider = QtWidgets.QSlider(self.groupBox_3)
        self.camHorShift_intSlider.setGeometry(QtCore.QRect(76, 50, 253, 20))
        self.camHorShift_intSlider.setMinimum(-100)
        self.camHorShift_intSlider.setMaximum(100)
        self.camHorShift_intSlider.setOrientation(QtCore.Qt.Horizontal)
        self.camHorShift_intSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.camHorShift_intSlider.setObjectName("camHorShift_intSlider")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(60, 20, 16, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(60, 45, 16, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(336, 45, 16, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(336, 20, 16, 21))
        self.label_28.setObjectName("label_28")
        self.camZoom_intSlider = QtWidgets.QSlider(self.groupBox_3)
        self.camZoom_intSlider.setGeometry(QtCore.QRect(12, 22, 41, 81))
        self.camZoom_intSlider.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.camZoom_intSlider.setMinimum(1)
        self.camZoom_intSlider.setMaximum(200)
        self.camZoom_intSlider.setPageStep(10)
        self.camZoom_intSlider.setProperty("value", 100)
        self.camZoom_intSlider.setOrientation(QtCore.Qt.Vertical)
        self.camZoom_intSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.camZoom_intSlider.setObjectName("camZoom_intSlider")
        self.camSensitivity_tField = QtWidgets.QLineEdit(self.groupBox_3)
        self.camSensitivity_tField.setGeometry(QtCore.QRect(120, 80, 36, 21))
        self.camSensitivity_tField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.camSensitivity_tField.setObjectName("camSensitivity_tField")
        self.softness_label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.softness_label_2.setGeometry(QtCore.QRect(50, 80, 71, 21))
        self.softness_label_2.setObjectName("softness_label_2")
        self.General_timing_gBox = QtWidgets.QGroupBox(self.centralwidget)
        self.General_timing_gBox.setGeometry(QtCore.QRect(10, 120, 364, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.General_timing_gBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.General_timing_gBox.setFont(font)
        self.General_timing_gBox.setFlat(False)
        self.General_timing_gBox.setCheckable(False)
        self.General_timing_gBox.setObjectName("General_timing_gBox")
        self.selKeyOnly_cBox = QtWidgets.QCheckBox(self.General_timing_gBox)
        self.selKeyOnly_cBox.setGeometry(QtCore.QRect(10, 60, 131, 17))
        self.selKeyOnly_cBox.setObjectName("selKeyOnly_cBox")
        self.minusTwoFrame_button = QtWidgets.QPushButton(self.General_timing_gBox)
        self.minusTwoFrame_button.setGeometry(QtCore.QRect(65, 20, 41, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.minusTwoFrame_button.setPalette(palette)
        self.minusTwoFrame_button.setObjectName("minusTwoFrame_button")
        self.minusOneFrame_button = QtWidgets.QPushButton(self.General_timing_gBox)
        self.minusOneFrame_button.setGeometry(QtCore.QRect(105, 20, 41, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.minusOneFrame_button.setPalette(palette)
        self.minusOneFrame_button.setObjectName("minusOneFrame_button")
        self.plusOneFrame_button = QtWidgets.QPushButton(self.General_timing_gBox)
        self.plusOneFrame_button.setGeometry(QtCore.QRect(205, 20, 41, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.plusOneFrame_button.setPalette(palette)
        self.plusOneFrame_button.setObjectName("plusOneFrame_button")
        self.plusTwoFrame_button = QtWidgets.QPushButton(self.General_timing_gBox)
        self.plusTwoFrame_button.setGeometry(QtCore.QRect(245, 20, 41, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.plusTwoFrame_button.setPalette(palette)
        self.plusTwoFrame_button.setObjectName("plusTwoFrame_button")
        self.timingEdit_tField = QtWidgets.QLineEdit(self.General_timing_gBox)
        self.timingEdit_tField.setGeometry(QtCore.QRect(150, 23, 51, 21))
        self.timingEdit_tField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timingEdit_tField.setObjectName("timingEdit_tField")
        self.moveToNext_cBox = QtWidgets.QCheckBox(self.General_timing_gBox)
        self.moveToNext_cBox.setGeometry(QtCore.QRect(220, 60, 101, 17))
        self.moveToNext_cBox.setObjectName("moveToNext_cBox")
        self.insertFrame_button = QtWidgets.QPushButton(self.General_timing_gBox)
        self.insertFrame_button.setGeometry(QtCore.QRect(150, 50, 51, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.insertFrame_button.setPalette(palette)
        self.insertFrame_button.setObjectName("insertFrame_button")
        self.minusTenFrame_button = QtWidgets.QPushButton(self.General_timing_gBox)
        self.minusTenFrame_button.setGeometry(QtCore.QRect(8, 20, 51, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.minusTenFrame_button.setPalette(palette)
        self.minusTenFrame_button.setObjectName("minusTenFrame_button")
        self.plusTenFrame_button = QtWidgets.QPushButton(self.General_timing_gBox)
        self.plusTenFrame_button.setGeometry(QtCore.QRect(292, 20, 51, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.plusTenFrame_button.setPalette(palette)
        self.plusTenFrame_button.setObjectName("plusTenFrame_button")
        self.General_quickButtons_gBox = QtWidgets.QGroupBox(self.centralwidget)
        self.General_quickButtons_gBox.setGeometry(QtCore.QRect(10, 200, 364, 131))
        self.General_quickButtons_gBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.General_quickButtons_gBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.General_quickButtons_gBox.setFont(font)
        self.General_quickButtons_gBox.setFlat(False)
        self.General_quickButtons_gBox.setCheckable(False)
        self.General_quickButtons_gBox.setObjectName("General_quickButtons_gBox")
        self.graphEditor_QB_button = QtWidgets.QPushButton(self.General_quickButtons_gBox)
        self.graphEditor_QB_button.setGeometry(QtCore.QRect(10, 80, 91, 26))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.graphEditor_QB_button.setPalette(palette)
        self.graphEditor_QB_button.setObjectName("graphEditor_QB_button")
        self.toggleTangents_QB_button = QtWidgets.QPushButton(self.General_quickButtons_gBox)
        self.toggleTangents_QB_button.setGeometry(QtCore.QRect(230, 80, 111, 26))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.toggleTangents_QB_button.setPalette(palette)
        self.toggleTangents_QB_button.setObjectName("toggleTangents_QB_button")
        self.dopeSheet_QB_button_2 = QtWidgets.QPushButton(self.General_quickButtons_gBox)
        self.dopeSheet_QB_button_2.setGeometry(QtCore.QRect(105, 80, 121, 26))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.dopeSheet_QB_button_2.setPalette(palette)
        self.dopeSheet_QB_button_2.setObjectName("dopeSheet_QB_button_2")
        self.selectionSets_button = QtWidgets.QPushButton(self.General_quickButtons_gBox)
        self.selectionSets_button.setGeometry(QtCore.QRect(180, 20, 111, 26))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.selectionSets_button.setPalette(palette)
        self.selectionSets_button.setObjectName("selectionSets_button")
        self.snap_button = QtWidgets.QPushButton(self.General_quickButtons_gBox)
        self.snap_button.setGeometry(QtCore.QRect(65, 20, 111, 26))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.snap_button.setPalette(palette)
        self.snap_button.setObjectName("snap_button")
        self.autoSaveDur_tField = QtWidgets.QLineEdit(self.General_quickButtons_gBox)
        self.autoSaveDur_tField.setEnabled(True)
        self.autoSaveDur_tField.setGeometry(QtCore.QRect(263, 110, 46, 21))
        self.autoSaveDur_tField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autoSaveDur_tField.setObjectName("autoSaveDur_tField")
        self.incremSave_cBox = QtWidgets.QCheckBox(self.General_quickButtons_gBox)
        self.incremSave_cBox.setGeometry(QtCore.QRect(48, 110, 121, 17))
        self.incremSave_cBox.setObjectName("incremSave_cBox")
        self.autoSave_cBox = QtWidgets.QCheckBox(self.General_quickButtons_gBox)
        self.autoSave_cBox.setGeometry(QtCore.QRect(182, 110, 79, 17))
        self.autoSave_cBox.setObjectName("autoSave_cBox")
        self.autoSave_text = QtWidgets.QLabel(self.General_quickButtons_gBox)
        self.autoSave_text.setGeometry(QtCore.QRect(315, 110, 31, 16))
        self.autoSave_text.setObjectName("autoSave_text")
        self.toggleImgPlanes_button = QtWidgets.QPushButton(self.General_quickButtons_gBox)
        self.toggleImgPlanes_button.setGeometry(QtCore.QRect(50, 50, 126, 26))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.toggleImgPlanes_button.setPalette(palette)
        self.toggleImgPlanes_button.setObjectName("toggleImgPlanes_button")
        self.ZVParentMaster_button = QtWidgets.QPushButton(self.General_quickButtons_gBox)
        self.ZVParentMaster_button.setGeometry(QtCore.QRect(180, 50, 126, 26))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.ZVParentMaster_button.setPalette(palette)
        self.ZVParentMaster_button.setObjectName("ZVParentMaster_button")
        self.toggleTangents_cBox = QtWidgets.QCheckBox(self.General_quickButtons_gBox)
        self.toggleTangents_cBox.setGeometry(QtCore.QRect(320, 60, 16, 17))
        self.toggleTangents_cBox.setText("")
        self.toggleTangents_cBox.setObjectName("toggleTangents_cBox")
        self.General_quickButtons_gBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.General_quickButtons_gBox_2.setGeometry(QtCore.QRect(10, 330, 364, 71))
        self.General_quickButtons_gBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.General_quickButtons_gBox_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.General_quickButtons_gBox_2.setFont(font)
        self.General_quickButtons_gBox_2.setFlat(False)
        self.General_quickButtons_gBox_2.setCheckable(False)
        self.General_quickButtons_gBox_2.setObjectName("General_quickButtons_gBox_2")
        self.weld_startEndFrame_cBox = QtWidgets.QCheckBox(self.General_quickButtons_gBox_2)
        self.weld_startEndFrame_cBox.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.weld_startEndFrame_cBox.setObjectName("weld_startEndFrame_cBox")
        self.weld_startFrame_tField = QtWidgets.QLineEdit(self.General_quickButtons_gBox_2)
        self.weld_startFrame_tField.setEnabled(False)
        self.weld_startFrame_tField.setGeometry(QtCore.QRect(130, 15, 61, 20))
        self.weld_startFrame_tField.setObjectName("weld_startFrame_tField")
        self.weld_button = QtWidgets.QPushButton(self.General_quickButtons_gBox_2)
        self.weld_button.setGeometry(QtCore.QRect(210, 20, 131, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.weld_button.setPalette(palette)
        self.weld_button.setObjectName("weld_button")
        self.weld_endFrame_tField = QtWidgets.QLineEdit(self.General_quickButtons_gBox_2)
        self.weld_endFrame_tField.setEnabled(False)
        self.weld_endFrame_tField.setGeometry(QtCore.QRect(130, 40, 61, 20))
        self.weld_endFrame_tField.setObjectName("weld_endFrame_tField")
        self.pushButton = QtWidgets.QPushButton(self.General_quickButtons_gBox_2)
        self.pushButton.setGeometry(QtCore.QRect(80, 15, 48, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.General_quickButtons_gBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 40, 48, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_2.setPalette(palette)
        self.pushButton_2.setObjectName("pushButton_2")
        RAT_mWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RAT_mWindow)
        QtCore.QMetaObject.connectSlotsByName(RAT_mWindow)

    def retranslateUi(self, RAT_mWindow):
        _translate = QtCore.QCoreApplication.translate
        RAT_mWindow.setWindowTitle(_translate("RAT_mWindow", "RedWire Animation Toolset"))
        self.General_keyBreakdown_gBox.setTitle(_translate("RAT_mWindow", "Tween"))
        self.keyOnMinusThree_button.setText(_translate("RAT_mWindow", "<<<"))
        self.keyOnMinusThree_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tweenKeyCommand -75\""))
        self.keyOnMinusThree_button.setProperty("-ann", _translate("RAT_mWindow", "\"Previous key 75%\""))
        self.keyOnMinusTwo_button.setText(_translate("RAT_mWindow", "<<"))
        self.keyOnMinusTwo_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tweenKeyCommand -50\""))
        self.keyOnMinusTwo_button.setProperty("-ann", _translate("RAT_mWindow", "\"Previous key 50%\""))
        self.key0_button.setText(_translate("RAT_mWindow", "< 0 >"))
        self.key0_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tweenKeyCommand 0\""))
        self.key0_button.setProperty("-ann", _translate("RAT_mWindow", "\"Both keys 50%\""))
        self.keyOnPlusTwo_button.setText(_translate("RAT_mWindow", ">>"))
        self.keyOnPlusTwo_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tweenKeyCommand 50\""))
        self.keyOnPlusTwo_button.setProperty("-ann", _translate("RAT_mWindow", "\"Next key 50%\""))
        self.keyOnPlusThree_button.setText(_translate("RAT_mWindow", ">>>"))
        self.keyOnPlusThree_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tweenKeyCommand 75\""))
        self.keyOnPlusThree_button.setProperty("-ann", _translate("RAT_mWindow", "\"Next key 75%\""))
        self.keyOnMinusOne_button.setText(_translate("RAT_mWindow", "<"))
        self.keyOnMinusOne_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tweenKeyCommand -25\""))
        self.keyOnMinusOne_button.setProperty("-ann", _translate("RAT_mWindow", "\"Previous key 25%\""))
        self.keyOnPlusOne_button.setText(_translate("RAT_mWindow", ">"))
        self.keyOnPlusOne_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tweenKeyCommand 25\""))
        self.keyOnPlusOne_button.setProperty("-ann", _translate("RAT_mWindow", "\"Next key 25%\""))
        self.keyBreakdown_intSlider.setProperty("-cc", _translate("RAT_mWindow", "\"RAT_tweenKeySlider\""))
        self.label_16.setText(_translate("RAT_mWindow", "%"))
        self.keyBreakdown_tField.setText(_translate("RAT_mWindow", "0"))
        self.keyBreakdown_tField.setProperty("-cc", _translate("RAT_mWindow", "RAT_updateSlider"))
        self.keyOnMinusThree_button_2.setText(_translate("RAT_mWindow", "-150"))
        self.keyOnMinusThree_button_2.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tweenKeyCommand -150\""))
        self.keyOnMinusThree_button_2.setProperty("-ann", _translate("RAT_mWindow", "\"Previous key 150%\""))
        self.keyOnMinusThree_button_3.setText(_translate("RAT_mWindow", "+150"))
        self.keyOnMinusThree_button_3.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tweenKeyCommand 150\""))
        self.keyOnMinusThree_button_3.setProperty("-ann", _translate("RAT_mWindow", "\"Next key 150%\""))
        self.keyOnMinusThree_button_4.setText(_translate("RAT_mWindow", "|>"))
        self.keyOnMinusThree_button_4.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tweenKeyCommand 100\""))
        self.keyOnMinusThree_button_4.setProperty("-ann", _translate("RAT_mWindow", "\"Next key 100%\""))
        self.keyOnMinusThree_button_5.setText(_translate("RAT_mWindow", "<|"))
        self.keyOnMinusThree_button_5.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tweenKeyCommand -100\""))
        self.keyOnMinusThree_button_5.setProperty("-ann", _translate("RAT_mWindow", "\"Previous key 100%\""))
        self.keyBreakdown_spinBox.setProperty("-m", _translate("RAT_mWindow", "0"))
        self.Advanced_curveCleaner_gBox.setTitle(_translate("RAT_mWindow", "Curves"))
        self.cleanCurves_button.setText(_translate("RAT_mWindow", "Clean Animation Curves"))
        self.cleanCurves_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_cleanCurves `textField -q -tx cleanCurves_tField`\""))
        self.cleanCurves_button.setProperty("-ann", _translate("RAT_mWindow", "\"Remove any redundant keys\""))
        self.flipCurves_button.setText(_translate("RAT_mWindow", "Flip Curves"))
        self.flipCurves_button.setProperty("-c", _translate("RAT_mWindow", "RAT_flipCurves"))
        self.flipCurves_button.setProperty("-ann", _translate("RAT_mWindow", "\"Flips all keys on chosen pivot\""))
        self.flipCurves_oMenu.setProperty("-cc", _translate("RAT_mWindow", "\"optionVar -sv \\\"RAT_flipCurves\\\" `optionMenu -q -v flipCurves_oMenu`\""))
        self.flipCurves_oMenu.setItemText(0, _translate("RAT_mWindow", "left"))
        self.flipCurves_oMenu.setItemText(1, _translate("RAT_mWindow", "right"))
        self.flipCurves_oMenu.setItemText(2, _translate("RAT_mWindow", "on 0"))
        self.flipCurves_oMenu.setItemText(3, _translate("RAT_mWindow", "selected key"))
        self.snapAnimation_button.setText(_translate("RAT_mWindow", "Snap Animation"))
        self.snapAnimation_button.setProperty("-c", _translate("RAT_mWindow", "RAT_snapAnim"))
        self.snapAnimation_button.setProperty("-ann", _translate("RAT_mWindow", "\"Offsets selected keys by chosen point\""))
        self.snapAnimPivot_oMenu.setProperty("-cc", _translate("RAT_mWindow", "\"optionVar -sv \\\"RAT_snapAnimation\\\" `optionMenu -q -v snapAnimPivot_oMenu`\""))
        self.snapAnimPivot_oMenu.setItemText(0, _translate("RAT_mWindow", "left"))
        self.snapAnimPivot_oMenu.setItemText(1, _translate("RAT_mWindow", "right"))
        self.softness_label.setText(_translate("RAT_mWindow", "Softness:"))
        self.curveSoftness_intSlider.setProperty("-cc", _translate("RAT_mWindow", "\"RAT_autoTangent;\""))
        self.flatStartEnd_cBox.setText(_translate("RAT_mWindow", "Flatten Start/End Keys"))
        self.curveSoftness_tField.setText(_translate("RAT_mWindow", "0"))
        self.curveSoftness_tField.setProperty("-cc", _translate("RAT_mWindow", " \"intSlider -e -v (float(`textField -q -text curveSoftness_tField`) *10) curveSoftness_intSlider; RAT_autoTangent\""))
        self.autoTangent_button.setText(_translate("RAT_mWindow", " GO!"))
        self.autoTangent_button.setProperty("-c", _translate("RAT_mWindow", "RAT_autoTangent"))
        self.autoTangent_button.setProperty("-ann", _translate("RAT_mWindow", "\"Adjusts selected keys tangents\""))
        self.cleanCurves_tField.setText(_translate("RAT_mWindow", ".001"))
        self.cleanCurves_tField.setProperty("-m", _translate("RAT_mWindow", "0"))
        self.label.setText(_translate("RAT_mWindow", "Tolerance:"))
        self.cac_modifyValue_grp.setTitle(_translate("RAT_mWindow", "        Value                                                                             "))
        self.cac_v_01_button.setText(_translate("RAT_mWindow", "Start to End"))
        self.cac_v_02_button.setText(_translate("RAT_mWindow", "End to Start"))
        self.cac_v_03_button.setText(_translate("RAT_mWindow", "Average"))
        self.cac_modifyTangent_grp.setTitle(_translate("RAT_mWindow", "        Tangent                                                                         "))
        self.cac_t_01_button.setText(_translate("RAT_mWindow", "Start to End"))
        self.cac_t_02_button.setText(_translate("RAT_mWindow", "End to Start"))
        self.cac_t_03_button.setText(_translate("RAT_mWindow", "Average"))
        self.cycle_anim_curve_button.setText(_translate("RAT_mWindow", " GO!"))
        self.cycle_anim_curve_button.setProperty("-c", _translate("RAT_mWindow", "cycleAnimCurves"))
        self.cycle_anim_curve_button.setProperty("-ann", _translate("RAT_mWindow", "\"Cycle Animation Curves\""))
        self.label_2.setText(_translate("RAT_mWindow", "Cycle Animation"))
        self.label_4.setText(_translate("RAT_mWindow", "Curves"))
        self.groupBox_3.setTitle(_translate("RAT_mWindow", "Zoom [Active Camera]"))
        self.camVerShift_intSlider.setProperty("-dc", _translate("RAT_mWindow", "\"setAttr (`lookThru -q`+\\\".verticalFilmOffset\\\") (`intSlider -q -v camVerShift_intSlider`/(float(`textField -q -tx camSensitivity_tField`)))\""))
        self.resetCamera_button.setText(_translate("RAT_mWindow", "Reset Camera"))
        self.resetCamera_button.setProperty("-c", _translate("RAT_mWindow", "RAT_zoomResetCam"))
        self.camHorShift_intSlider.setProperty("-dc", _translate("RAT_mWindow", "\"setAttr (`lookThru -q`+\\\".horizontalFilmOffset\\\") (`intSlider -q -v camHorShift_intSlider` /(float(`textField -q -tx camSensitivity_tField`)))\""))
        self.label_25.setText(_translate("RAT_mWindow", "V"))
        self.label_26.setText(_translate("RAT_mWindow", "H"))
        self.label_27.setText(_translate("RAT_mWindow", "H"))
        self.label_28.setText(_translate("RAT_mWindow", "V"))
        self.camZoom_intSlider.setProperty("-dc", _translate("RAT_mWindow", "\"setAttr (`lookThru -q` +\\\".overscan\\\") (`intSlider -q -v camZoom_intSlider`/(float(`textField -q -tx camSensitivity_tField`)))\""))
        self.camSensitivity_tField.setText(_translate("RAT_mWindow", "250"))
        self.softness_label_2.setText(_translate("RAT_mWindow", "Sensitivity:"))
        self.General_timing_gBox.setTitle(_translate("RAT_mWindow", "Timing"))
        self.selKeyOnly_cBox.setText(_translate("RAT_mWindow", "Selected Key Only"))
        self.minusTwoFrame_button.setText(_translate("RAT_mWindow", "-2f"))
        self.minusTwoFrame_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_keyNudge -2\""))
        self.minusTwoFrame_button.setProperty("-ann", _translate("RAT_mWindow", "\"Shift keys by -2 frames\""))
        self.minusOneFrame_button.setText(_translate("RAT_mWindow", "-1f"))
        self.minusOneFrame_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_keyNudge -1\""))
        self.minusOneFrame_button.setProperty("-ann", _translate("RAT_mWindow", "\"Shift keys by -1 frames\""))
        self.plusOneFrame_button.setText(_translate("RAT_mWindow", "+1f"))
        self.plusOneFrame_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_keyNudge 1\""))
        self.plusOneFrame_button.setProperty("-ann", _translate("RAT_mWindow", "\"Shift keys by 1 frames\""))
        self.plusTwoFrame_button.setText(_translate("RAT_mWindow", "+2f"))
        self.plusTwoFrame_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_keyNudge 2\""))
        self.plusTwoFrame_button.setProperty("-ann", _translate("RAT_mWindow", "\"Shift keys by 2 frames\""))
        self.timingEdit_tField.setText(_translate("RAT_mWindow", "0"))
        self.moveToNext_cBox.setText(_translate("RAT_mWindow", "Move To Next"))
        self.insertFrame_button.setText(_translate("RAT_mWindow", "Shift"))
        self.insertFrame_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_keyNudge `textField -q -text timingEdit_tField`\""))
        self.minusTenFrame_button.setText(_translate("RAT_mWindow", "-10f"))
        self.minusTenFrame_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_keyNudge -10\""))
        self.minusTenFrame_button.setProperty("-ann", _translate("RAT_mWindow", "\"Shift keys by -10 frames\""))
        self.plusTenFrame_button.setText(_translate("RAT_mWindow", "+10f"))
        self.plusTenFrame_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_keyNudge 10\""))
        self.plusTenFrame_button.setProperty("-ann", _translate("RAT_mWindow", "\"Shift keys by 10 frames\""))
        self.General_quickButtons_gBox.setTitle(_translate("RAT_mWindow", "Quick Buttons"))
        self.graphEditor_QB_button.setText(_translate("RAT_mWindow", "Graph Editor"))
        self.graphEditor_QB_button.setProperty("-c", _translate("RAT_mWindow", "\"GraphEditor; tearOffPanel \\\"Graph Editor\\\" \\\"graphEditor\\\" true\""))
        self.toggleTangents_QB_button.setText(_translate("RAT_mWindow", "Toggle Tangents"))
        self.toggleTangents_QB_button.setProperty("-c", _translate("RAT_mWindow", "\"RAT_tangentConvert\""))
        self.toggleTangents_QB_button.setProperty("-ann", _translate("RAT_mWindow", "\"Selected curves tangents from Step to Plateau\""))
        self.dopeSheet_QB_button_2.setText(_translate("RAT_mWindow", "Camera Sequencer"))
        self.dopeSheet_QB_button_2.setProperty("-c", _translate("RAT_mWindow", "\"SequenceEditor; tearOffPanel \\\"Camera Sequencer\\\" \\\"sequenceEditorPanel\\\" true\""))
        self.selectionSets_button.setText(_translate("RAT_mWindow", "Selection Sets"))
        self.selectionSets_button.setProperty("-c", _translate("RAT_mWindow", "RAT_selectionSets"))
        self.snap_button.setText(_translate("RAT_mWindow", "Snap"))
        self.snap_button.setProperty("-c", _translate("RAT_mWindow", "RAT_snapObjs"))
        self.snap_button.setProperty("-ann", _translate("RAT_mWindow", "\"Snaps objects to last selected object\""))
        self.autoSaveDur_tField.setText(_translate("RAT_mWindow", "10"))
        self.autoSaveDur_tField.setProperty("-cc", _translate("RAT_mWindow", "RAT_autoSave"))
        self.incremSave_cBox.setText(_translate("RAT_mWindow", "Incremental Save"))
        self.incremSave_cBox.setProperty("-onc", _translate("RAT_mWindow", "\"optionVar -intValue isIncrementalSaveEnabled 1\""))
        self.incremSave_cBox.setProperty("-ofc", _translate("RAT_mWindow", "\"optionVar -intValue isIncrementalSaveEnabled 0\""))
        self.autoSave_cBox.setText(_translate("RAT_mWindow", "Auto Save"))
        self.autoSave_cBox.setProperty("-onc", _translate("RAT_mWindow", "\"RAT_autoSave; optionVar -iv autoSaveEnable true; autoSave -en true\""))
        self.autoSave_cBox.setProperty("-ofc", _translate("RAT_mWindow", "\"optionVar -iv autoSaveEnable false; autoSave -en false\""))
        self.autoSave_text.setText(_translate("RAT_mWindow", "mins"))
        self.toggleImgPlanes_button.setText(_translate("RAT_mWindow", "Toggle Imageplane"))
        self.toggleImgPlanes_button.setProperty("-c", _translate("RAT_mWindow", "RAT_toggleImgPlanes"))
        self.ZVParentMaster_button.setText(_translate("RAT_mWindow", "ZV Parent Master"))
        self.ZVParentMaster_button.setProperty("-c", _translate("RAT_mWindow", "\"python(\\\"import ZvParentMaster\\\"); python(\\\"ZvParentMaster.ZvParentMaster()\\\")\""))
        self.toggleTangents_cBox.setProperty("-m", _translate("RAT_mWindow", "0"))
        self.General_quickButtons_gBox_2.setTitle(_translate("RAT_mWindow", "Weld"))
        self.weld_startEndFrame_cBox.setText(_translate("RAT_mWindow", "Range?"))
        self.weld_startEndFrame_cBox.setProperty("-cc", _translate("RAT_mWindow", "\"optionVar -iv \\\"RAT_weldRangeEnabled\\\" (`checkBox -q -v weld_startEndFrame_cBox`)\""))
        self.weld_button.setText(_translate("RAT_mWindow", "Weld"))
        self.weld_button.setProperty("-c", _translate("RAT_mWindow", "RAT_weldControls"))
        self.weld_button.setProperty("-ann", _translate("RAT_mWindow", "\"Weld selected objects to previous frame position\""))
        self.pushButton.setText(_translate("RAT_mWindow", "Start :"))
        self.pushButton.setProperty("-c", _translate("RAT_mWindow", "\"textField -e -tx `currentTime -q` weld_startFrame_tField\""))
        self.pushButton_2.setText(_translate("RAT_mWindow", "End :"))
        self.pushButton_2.setProperty("-c", _translate("RAT_mWindow", "\"textField -e -tx `currentTime -q` weld_endFrame_tField\""))

