# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:/.core/dev/tapp/Tapp/Maya/modelling/resources/dialog.ui'
#
# Created: Wed Feb 01 16:15:26 2017
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(367, 591)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_7.addWidget(self.line_8)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_9.sizePolicy().hasHeightForWidth())
        self.line_9.setSizePolicy(sizePolicy)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_7.addWidget(self.line_9)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.detachSeparate_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detachSeparate_pushButton.sizePolicy().hasHeightForWidth())
        self.detachSeparate_pushButton.setSizePolicy(sizePolicy)
        self.detachSeparate_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detachSeparate_pushButton.setFont(font)
        self.detachSeparate_pushButton.setObjectName("detachSeparate_pushButton")
        self.verticalLayout.addWidget(self.detachSeparate_pushButton)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scatter_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scatter_pushButton.sizePolicy().hasHeightForWidth())
        self.scatter_pushButton.setSizePolicy(sizePolicy)
        self.scatter_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scatter_pushButton.setFont(font)
        self.scatter_pushButton.setObjectName("scatter_pushButton")
        self.gridLayout_2.addWidget(self.scatter_pushButton, 0, 0, 1, 1)
        self.scatterInfo_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scatterInfo_pushButton.sizePolicy().hasHeightForWidth())
        self.scatterInfo_pushButton.setSizePolicy(sizePolicy)
        self.scatterInfo_pushButton.setMinimumSize(QtCore.QSize(30, 15))
        self.scatterInfo_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.scatterInfo_pushButton.setObjectName("scatterInfo_pushButton")
        self.gridLayout_2.addWidget(self.scatterInfo_pushButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.uvDeluxe_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uvDeluxe_pushButton.sizePolicy().hasHeightForWidth())
        self.uvDeluxe_pushButton.setSizePolicy(sizePolicy)
        self.uvDeluxe_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.uvDeluxe_pushButton.setFont(font)
        self.uvDeluxe_pushButton.setObjectName("uvDeluxe_pushButton")
        self.verticalLayout.addWidget(self.uvDeluxe_pushButton)
        self.instanceAlongCurve_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.instanceAlongCurve_pushButton.setObjectName("instanceAlongCurve_pushButton")
        self.verticalLayout.addWidget(self.instanceAlongCurve_pushButton)
        self.rivet_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.rivet_pushButton.setObjectName("rivet_pushButton")
        self.verticalLayout.addWidget(self.rivet_pushButton)
        self.curvOnMesh_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.curvOnMesh_pushButton.setObjectName("curvOnMesh_pushButton")
        self.verticalLayout.addWidget(self.curvOnMesh_pushButton)
        self.plotCurve_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotCurve_pushButton.setObjectName("plotCurve_pushButton")
        self.verticalLayout.addWidget(self.plotCurve_pushButton)
        self.edgesToCurves_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.edgesToCurves_pushButton.setObjectName("edgesToCurves_pushButton")
        self.verticalLayout.addWidget(self.edgesToCurves_pushButton)
        self.curveToPoly_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.curveToPoly_pushButton.setObjectName("curveToPoly_pushButton")
        self.verticalLayout.addWidget(self.curveToPoly_pushButton)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_5.addWidget(self.line_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.loadPositionVerts_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadPositionVerts_pushButton.sizePolicy().hasHeightForWidth())
        self.loadPositionVerts_pushButton.setSizePolicy(sizePolicy)
        self.loadPositionVerts_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.loadPositionVerts_pushButton.setObjectName("loadPositionVerts_pushButton")
        self.gridLayout.addWidget(self.loadPositionVerts_pushButton, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 1, 1)
        self.positionVerts_label = QtWidgets.QLabel(self.centralwidget)
        self.positionVerts_label.setAlignment(QtCore.Qt.AlignCenter)
        self.positionVerts_label.setObjectName("positionVerts_label")
        self.gridLayout.addWidget(self.positionVerts_label, 0, 2, 1, 1)
        self.loadUpVert_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadUpVert_pushButton.sizePolicy().hasHeightForWidth())
        self.loadUpVert_pushButton.setSizePolicy(sizePolicy)
        self.loadUpVert_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.loadUpVert_pushButton.setObjectName("loadUpVert_pushButton")
        self.gridLayout.addWidget(self.loadUpVert_pushButton, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 1, 1, 1)
        self.upVert_label = QtWidgets.QLabel(self.centralwidget)
        self.upVert_label.setAlignment(QtCore.Qt.AlignCenter)
        self.upVert_label.setObjectName("upVert_label")
        self.gridLayout.addWidget(self.upVert_label, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.locator_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.locator_checkBox.setEnabled(True)
        self.locator_checkBox.setChecked(False)
        self.locator_checkBox.setObjectName("locator_checkBox")
        self.horizontalLayout.addWidget(self.locator_checkBox)
        self.mesh_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.mesh_checkBox.setEnabled(True)
        self.mesh_checkBox.setChecked(False)
        self.mesh_checkBox.setObjectName("mesh_checkBox")
        self.horizontalLayout.addWidget(self.mesh_checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.create_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_pushButton.sizePolicy().hasHeightForWidth())
        self.create_pushButton.setSizePolicy(sizePolicy)
        self.create_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_pushButton.setFont(font)
        self.create_pushButton.setObjectName("create_pushButton")
        self.verticalLayout.addWidget(self.create_pushButton)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_6.addWidget(self.line_6)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_6.addWidget(self.line_7)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.psdImport_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.psdImport_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.psdImport_pushButton.setObjectName("psdImport_pushButton")
        self.horizontalLayout_2.addWidget(self.psdImport_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tapp Modelling"))
        self.label_3.setText(_translate("MainWindow", "General"))
        self.detachSeparate_pushButton.setText(_translate("MainWindow", "Detach/Separate"))
        self.scatter_pushButton.setText(_translate("MainWindow", "Scatter"))
        self.scatterInfo_pushButton.setText(_translate("MainWindow", "?"))
        self.uvDeluxe_pushButton.setText(_translate("MainWindow", "UV Deluxe"))
        self.instanceAlongCurve_pushButton.setText(_translate("MainWindow", "Instance Along Curve"))
        self.rivet_pushButton.setText(_translate("MainWindow", "Rivet"))
        self.curvOnMesh_pushButton.setText(_translate("MainWindow", "Draw Curve on Mesh"))
        self.plotCurve_pushButton.setText(_translate("MainWindow", "Hart Plot Curve"))
        self.edgesToCurves_pushButton.setText(_translate("MainWindow", "Edges to Curves"))
        self.curveToPoly_pushButton.setText(_translate("MainWindow", "Curve to Poly"))
        self.label.setText(_translate("MainWindow", "Triangulate Pivot"))
        self.loadPositionVerts_pushButton.setText(_translate("MainWindow", "Load Position Verts"))
        self.positionVerts_label.setText(_translate("MainWindow", "No Position Verts loaded!"))
        self.loadUpVert_pushButton.setText(_translate("MainWindow", "Load Upvector Vert"))
        self.upVert_label.setText(_translate("MainWindow", "No Upvector Vert loaded!"))
        self.locator_checkBox.setText(_translate("MainWindow", "Create Locator"))
        self.mesh_checkBox.setText(_translate("MainWindow", "Change Mesh Pivot"))
        self.create_pushButton.setText(_translate("MainWindow", "Create"))
        self.label_2.setText(_translate("MainWindow", "PSD Import"))
        self.psdImport_pushButton.setText(_translate("MainWindow", "Import prepared layers"))
