# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:/.core/dev/tapp/Tapp/Maya/modelling\resources\dialog.ui'
#
# Created: Mon Aug 15 18:32:33 2016
#      by: Qt UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(256, 616)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_7.addWidget(self.line_8)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_9.sizePolicy().hasHeightForWidth())
        self.line_9.setSizePolicy(sizePolicy)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_7.addWidget(self.line_9)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.detachSeparate_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detachSeparate_pushButton.sizePolicy().hasHeightForWidth())
        self.detachSeparate_pushButton.setSizePolicy(sizePolicy)
        self.detachSeparate_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detachSeparate_pushButton.setFont(font)
        self.detachSeparate_pushButton.setObjectName("detachSeparate_pushButton")
        self.verticalLayout.addWidget(self.detachSeparate_pushButton)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scatter_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scatter_pushButton.sizePolicy().hasHeightForWidth())
        self.scatter_pushButton.setSizePolicy(sizePolicy)
        self.scatter_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scatter_pushButton.setFont(font)
        self.scatter_pushButton.setObjectName("scatter_pushButton")
        self.gridLayout_2.addWidget(self.scatter_pushButton, 0, 0, 1, 1)
        self.scatterInfo_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scatterInfo_pushButton.sizePolicy().hasHeightForWidth())
        self.scatterInfo_pushButton.setSizePolicy(sizePolicy)
        self.scatterInfo_pushButton.setMinimumSize(QtCore.QSize(30, 25))
        self.scatterInfo_pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.scatterInfo_pushButton.setObjectName("scatterInfo_pushButton")
        self.gridLayout_2.addWidget(self.scatterInfo_pushButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.uvDeluxe_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uvDeluxe_pushButton.sizePolicy().hasHeightForWidth())
        self.uvDeluxe_pushButton.setSizePolicy(sizePolicy)
        self.uvDeluxe_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.uvDeluxe_pushButton.setFont(font)
        self.uvDeluxe_pushButton.setObjectName("uvDeluxe_pushButton")
        self.verticalLayout.addWidget(self.uvDeluxe_pushButton)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_12.sizePolicy().hasHeightForWidth())
        self.line_12.setSizePolicy(sizePolicy)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_9.addWidget(self.line_12)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_13.sizePolicy().hasHeightForWidth())
        self.line_13.setSizePolicy(sizePolicy)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_9.addWidget(self.line_13)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.symmetry_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symmetry_pushButton.sizePolicy().hasHeightForWidth())
        self.symmetry_pushButton.setSizePolicy(sizePolicy)
        self.symmetry_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.symmetry_pushButton.setFont(font)
        self.symmetry_pushButton.setObjectName("symmetry_pushButton")
        self.verticalLayout.addWidget(self.symmetry_pushButton)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_10.sizePolicy().hasHeightForWidth())
        self.line_10.setSizePolicy(sizePolicy)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_8.addWidget(self.line_10)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_11.sizePolicy().hasHeightForWidth())
        self.line_11.setSizePolicy(sizePolicy)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_8.addWidget(self.line_11)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mirrorBlendshape_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mirrorBlendshape_pushButton.sizePolicy().hasHeightForWidth())
        self.mirrorBlendshape_pushButton.setSizePolicy(sizePolicy)
        self.mirrorBlendshape_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mirrorBlendshape_pushButton.setFont(font)
        self.mirrorBlendshape_pushButton.setObjectName("mirrorBlendshape_pushButton")
        self.horizontalLayout_3.addWidget(self.mirrorBlendshape_pushButton)
        self.UVSymmetry_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UVSymmetry_pushButton.sizePolicy().hasHeightForWidth())
        self.UVSymmetry_pushButton.setSizePolicy(sizePolicy)
        self.UVSymmetry_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UVSymmetry_pushButton.setFont(font)
        self.UVSymmetry_pushButton.setObjectName("UVSymmetry_pushButton")
        self.horizontalLayout_3.addWidget(self.UVSymmetry_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_5.addWidget(self.line_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.loadPositionVerts_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadPositionVerts_pushButton.sizePolicy().hasHeightForWidth())
        self.loadPositionVerts_pushButton.setSizePolicy(sizePolicy)
        self.loadPositionVerts_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loadPositionVerts_pushButton.setObjectName("loadPositionVerts_pushButton")
        self.gridLayout.addWidget(self.loadPositionVerts_pushButton, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 1, 1)
        self.positionVerts_label = QtWidgets.QLabel(self.centralwidget)
        self.positionVerts_label.setAlignment(QtCore.Qt.AlignCenter)
        self.positionVerts_label.setObjectName("positionVerts_label")
        self.gridLayout.addWidget(self.positionVerts_label, 0, 2, 1, 1)
        self.loadUpVert_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadUpVert_pushButton.sizePolicy().hasHeightForWidth())
        self.loadUpVert_pushButton.setSizePolicy(sizePolicy)
        self.loadUpVert_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loadUpVert_pushButton.setObjectName("loadUpVert_pushButton")
        self.gridLayout.addWidget(self.loadUpVert_pushButton, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 1, 1, 1)
        self.upVert_label = QtWidgets.QLabel(self.centralwidget)
        self.upVert_label.setAlignment(QtCore.Qt.AlignCenter)
        self.upVert_label.setObjectName("upVert_label")
        self.gridLayout.addWidget(self.upVert_label, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.locator_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.locator_checkBox.setEnabled(True)
        self.locator_checkBox.setChecked(False)
        self.locator_checkBox.setObjectName("locator_checkBox")
        self.horizontalLayout.addWidget(self.locator_checkBox)
        self.mesh_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.mesh_checkBox.setEnabled(True)
        self.mesh_checkBox.setChecked(False)
        self.mesh_checkBox.setObjectName("mesh_checkBox")
        self.horizontalLayout.addWidget(self.mesh_checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.create_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_pushButton.sizePolicy().hasHeightForWidth())
        self.create_pushButton.setSizePolicy(sizePolicy)
        self.create_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_pushButton.setFont(font)
        self.create_pushButton.setObjectName("create_pushButton")
        self.verticalLayout.addWidget(self.create_pushButton)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_6.addWidget(self.line_6)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_6.addWidget(self.line_7)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.roadkill_useLSCM_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.roadkill_useLSCM_checkBox.setObjectName("roadkill_useLSCM_checkBox")
        self.horizontalLayout_2.addWidget(self.roadkill_useLSCM_checkBox)
        self.roadkill_dontFillHoles_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.roadkill_dontFillHoles_checkBox.setObjectName("roadkill_dontFillHoles_checkBox")
        self.horizontalLayout_2.addWidget(self.roadkill_dontFillHoles_checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.roadkill_liveUnwrap_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.roadkill_liveUnwrap_checkBox.setObjectName("roadkill_liveUnwrap_checkBox")
        self.verticalLayout.addWidget(self.roadkill_liveUnwrap_checkBox)
        self.roadKill_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roadKill_pushButton.sizePolicy().hasHeightForWidth())
        self.roadKill_pushButton.setSizePolicy(sizePolicy)
        self.roadKill_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.roadKill_pushButton.setFont(font)
        self.roadKill_pushButton.setObjectName("roadKill_pushButton")
        self.verticalLayout.addWidget(self.roadKill_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tapp Modelling"))
        self.label_3.setText(_translate("MainWindow", "General"))
        self.detachSeparate_pushButton.setText(_translate("MainWindow", "Detach/Separate"))
        self.scatter_pushButton.setText(_translate("MainWindow", "Scatter"))
        self.scatterInfo_pushButton.setText(_translate("MainWindow", "?"))
        self.uvDeluxe_pushButton.setText(_translate("MainWindow", "UV Deluxe"))
        self.label_5.setText(_translate("MainWindow", "UV-Destructive"))
        self.symmetry_pushButton.setText(_translate("MainWindow", "Symmetry"))
        self.label_4.setText(_translate("MainWindow", "UV-Preserving"))
        self.mirrorBlendshape_pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select all blendshapes first, then the original mesh last!</p></body></html>"))
        self.mirrorBlendshape_pushButton.setText(_translate("MainWindow", "Mirror Blendshape"))
        self.UVSymmetry_pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the edited mesh first, then the original mesh last!</p></body></html>"))
        self.UVSymmetry_pushButton.setText(_translate("MainWindow", "Symmetry"))
        self.label.setText(_translate("MainWindow", "Triangulate Pivot"))
        self.loadPositionVerts_pushButton.setText(_translate("MainWindow", "Load Position Verts"))
        self.positionVerts_label.setText(_translate("MainWindow", "No Position Verts loaded!"))
        self.loadUpVert_pushButton.setText(_translate("MainWindow", "Load Upvector Vert"))
        self.upVert_label.setText(_translate("MainWindow", "No Upvector Vert loaded!"))
        self.locator_checkBox.setText(_translate("MainWindow", "Create Locator"))
        self.mesh_checkBox.setText(_translate("MainWindow", "Change Mesh Pivot"))
        self.create_pushButton.setText(_translate("MainWindow", "Create"))
        self.label_2.setText(_translate("MainWindow", "RoadKill"))
        self.roadkill_useLSCM_checkBox.setText(_translate("MainWindow", "Use LSCM"))
        self.roadkill_dontFillHoles_checkBox.setText(_translate("MainWindow", "Don\'t Fill Holes"))
        self.roadkill_liveUnwrap_checkBox.setText(_translate("MainWindow", "Live Unwrap"))
        self.roadKill_pushButton.setText(_translate("MainWindow", "Unwrap"))
